### ISSUE TITLE
Error when importing javafx: javafx.application does not exist

### ISSUE THREAD

**Issue by wjacobw** [nus-cs2103-AY2324S1/forum#106]
I tried to import javafx by following the guide but the package is not detected with an error : error: package javafx.application does not exist import javafx.application.Application;

```
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

repositories {
    mavenCentral()
}

javafx {
    version = '17.0.2'
    modules = [ 'javafx.controls' ]
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
    String javaFxVersion = '17.0.7'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "skipped", "failed"

        showExceptions true
        exceptionFormat "full"
        showCauses true
        showStackTraces true
        showStandardStreams = false
    }
}

application {
    mainClass.set("seedu.duke.Duke")
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
    dependsOn("distZip", "distTar")
}

run{
    standardInput = System.in
}

javafx {
    version = '17'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass.set("seedu.Duke")
}
```

```java
package duke;

import java.io.IOException;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class Duke extends Application{
```

**Comment by damithc** [comment]
@wjacobw This can help with the formatting of your post https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by wjacobw** [comment]
> @wjacobw This can help with the formatting of your post https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Thank you for the suggestion! I have changed my question format according to it.

**Comment by jianrong7** [comment]
Perhaps you didn't create a `start` method in `Duke` which overrides the method in the `Application` class you are extending from.

**Comment by damithc** [comment]
> Thank you for the suggestion! I have changed my question format according to it.

@wjacobw I tidied up your post further (although still feels like it's lacking in details)

While waiting for inputs from others, here are some things you can try:
* Push the code to your fork and share the link here so that other can try to replicate the problem.
* If using Intellij, try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij

**Comment by keaganpzh** [comment]
Check that you are using the correct version of Java (JDK 11). If you are using macOS on Apple Silicon do also follow the advisory given here:

https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html

**Comment by wjacobw** [comment]
> Perhaps you didn't create a `start` method in `Duke` which overrides the method in the `Application` class you are extending from.

I have made the start method in Duke, but still same problem.

**Comment by wjacobw** [comment]
> Check that you are using the correct version of Java (JDK 11). If you are using macOS on Apple Silicon do also follow the advisory given here:
> 
> https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html

I am using openJDK version 11.0.20. Thank you for the recommendation, I will look through it.

**Comment by wjacobw** [comment]
> > Thank you for the suggestion! I have changed my question format according to it.
> 
> @wjacobw I tidied up your post further (although still feels like it's lacking in details)
> 
> While waiting for inputs from others, here are some things you can try:
> 
>     * Push the code to your fork and share the link here so that other can try to replicate the problem.
> 
>     * If using Intellij, try these 'common remedies' one-at-a-time in this order:
>       
>       * Choose `File` -> `Invalidate caches`
>       * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij

Thank you. Seems like the problem is with the JDK version that I used. I used JDK version 11.0.20 instead of the one that is recommended in the website.

**Comment by wjacobw** [comment]
Solved. Problem was with my JDK Version.

**Comment by cheeheng** [comment]
Hi. I am a student from a previous batch. I would like to mention that it would have been useful to mention the operating system you are using because some issues regarding whether JavaFX runs properly could be operating system-specific. One example could be found in the advisory for Mac users in [the CS2103T programming languages webpage](https://nus-cs2103-ay2324s1.github.io/website/admin/programmingLanguages.html), as mentioned by @keaganpzh.

~I would also like to point out that in the gradle file that the original poster provided, the version of JavaFX should be 11 instead of 17.~ Edit: we are using JavaFX 17 instead of JavaFX 11 this semester as pointed out by Prof Damith. 

Observe that the gradle file sent by the original poster has conflicting values of version, 17.0.2 and 17.0.7, which would result in version conflict. How Gradle resolves version conflicts can be found [here](https://stackoverflow.com/questions/29374885/multiple-version-of-dependencies-in-gradle).

It may also cause difficulties in debugging if the cause is due to a bug fix in some package of JavaFX in version 17.0.X.

The relevant snippets from the original poster's gradle file can be found here:

```
javafx {
    version = '17.0.2'
    modules = [ 'javafx.controls' ]
}

dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.10.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.10.0'
    String javaFxVersion = '17.0.7'
```

```
javafx {
    version = '17'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```

**Comment by damithc** [comment]
@cheeheng This time we are using JavaFX 17 (but still JDK 11).

**Comment by cheeheng** [comment]
Thanks prof for correcting. I have edited the message to fix the issue.
