### ISSUE TITLE
Fix list appearance

### ISSUE THREAD

**Issue by MadLamprey** [nus-cs2103-AY2324S1/forum#113]
<img width="399" alt="Screenshot 2023-09-06 at 9 05 31 PM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/114080910/347deba8-8420-4201-9e3a-e4b75e32d72c">

The first time I display the list, it displays correctly. Thereafter, it shows part of it only. I understand that it has to do with the heights of the ScrollPane and the VBox but I am unable to figure out how to solve it.

**Comment by Singa-pirate** [comment]
Changing the type of the text from **Label** to **Text** worked for me.

From some online posts, these two types are different because **Label** is a *Control*, whereas **Text** is a *Shape*. I'm not entirely sure why **Label** will be automatically truncated. My interpretation is that, the properties of a **Label** are binded to its parent and siblings, thus may be affected by other controls in the environment. However the dimensions of a **Text** are fixed once it is created. Maybe someone who can explain more accurately can help chime in here.

**Text** does not have some of the customisable properties of **Label**. I replaced those properties with **wrappingWidth** and **textAlignment** to make sure it looks the same as before.

**Comment by MadLamprey** [comment]
Ahh thank you it worked by using Text instead of Label.
