### ISSUE TITLE
Question on Gradle Wrapper jar file

### ISSUE THREAD

**Issue by WZWren** [nus-cs2103-AY2324S1/forum#116]
I noticed while we were adding gradle support for the iP that we push the gradle-wrapper.jar file into the repository. This is a binary file that's generated when one of the [Gradle wrapper scripts](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html) run for the first time.

The documentation itself does say we should push this to the remote, but doesn't this directly contradict the idea that we shouldn't push binaries to the repository? Can't we get the users to generate this file themselves?

**Comment by damithc** [comment]
Good point @WZWren Committing binary files is not usual, but we make an exception in this case, for convenience e.g., to make it easier for students to add Gradle support, to make it easier for someone to reproduce an error someone else is facing, by cloning the latter's fork.
Since the file is small and doesn't change during this project duration, the negative effects of versioning it are not as significant.

**Comment by WZWren** [comment]
Oh ok. Thanks prof!
