### ISSUE TITLE
Another unsupported JavaFX configuration error

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#122]
My branch:
https://github.com/JasonRay168/ip/tree/branch-Level-10

I got this error again, similar to the last issue, but this time was because I changed the main class in launcher from Duke to Main
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/75bffb29-9c15-4f37-bd45-fd394a95e567)

I have made sure all constructors are empty, so I don't know what caused the error. I have migrated the methods from the chatbot file to the Main.java and MainWindow.java files, but the issue still persists.

**Comment by junhonglow** [comment]
You currently have your image extensions as .png in MainWindow whereas your resources are in jpg format.
```Java
    private Image userImage = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
    private Image dukeImage = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));
```
Additionally, after fixing that error you might need to add the FXML annotation to the DialogBox class, as I ran into another error without those tags.

**Comment by JasonRay168** [comment]
I'm sorry, but that didn't fix the issue 😢 
I found this weird behavior, as you can see:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/9ffdff64-a84f-4b4f-8ad5-ca888e54a561)
The 2 fields dialog and displayPicture were used, but the corresponding field declarations at the top was not highlighted purple, meaning it is not used

Also, the terminal said there's an error at that line
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/113493308/8ce09217-2a6e-466d-8ad5-331f94ae7e7a)

Edit: Where should I put the @FXML annotation in the DialogBox class?

**Comment by ivyy-poison** [comment]
Currently facing a similar error, not sure how to solve also. May i ask if you are using a Macbook as well? Seems like the way JavaFx is compiled is with the x86_64, while i'm running on an ARM64 architecture.

A strange thing that occurs on my end however, is that suppose you simply ran gradle clean build, then directly access the shadow jar file using java -jar, it still works fine. Therefore it is only when running using gradle, that was the issue.

**Comment by WZWren** [comment]
@JasonRay You need to add the `@FXML` labels to `dialog` and `displayPicture` - otherwise your FXML files will not be able to detect the variables.

You can see this from your error message - its leading you to line 41 with a `NullPointerException` - you are calling `setText` on an uninitialized label, so it's not automatically loading in from the FXML file.

> The 2 fields dialog and displayPicture were used, but the corresponding field declarations at the top was not highlighted purple, meaning it is not used

Regarding this, the IDE doesn't seem to detect variable usage in FXML files, even with the `@FXML` tag - don't be too alarmed by this.

**Comment by raydenlim** [comment]
It says u have a nullpointer at MainWindow. U might want to check that class out :)
Not sure if it is correct, but u haven't initialise ur ui in MainWindow.java. That may be causing the nullpointer issue

**Comment by ElginTZM** [comment]
There might be an issue with your MainWindow.fxml at line 9 from the first error message. This may result in the variables not loading in, causing the NullPointerException.

**Comment by damithc** [comment]
General tip: If you are facing issues with JavaFx/GUI, you can compare your code to code of students who posted in #101 , to figure out what you are doing differently from them, which might help you locate the problem.

**Comment by cheeheng** [comment]
> I'm sorry, but that didn't fix the issue 😢 I found this weird behavior, as you can see: ![image](https://user-images.githubusercontent.com/113493308/266482266-9ffdff64-a84f-4b4f-8ad5-ca888e54a561.png) The 2 fields dialog and displayPicture were used, but the corresponding field declarations at the top was not highlighted purple, meaning it is not used
> 
> Also, the terminal said there's an error at that line ![image](https://user-images.githubusercontent.com/113493308/266482509-8ce09217-2a6e-466d-8ad5-331f94ae7e7a.png)
> 
> Edit: Where should I put the @FXML annotation in the DialogBox class?

Hi. I am a student from a previous batch. I would like to point out that you could use the fenced code blocks syntax (using three backticks to surround the code) to denote code blocks so that when others try to fix your issue and wish to copy the code to test the code, they do not have to copy the code manually. Here is a sample snippet of code using the fenced code blocks syntax.

```java
public static void main(String[] args) {
}
```

The corresponding Markdown is as follows:
\```java
public static void main(String[] args) {
}
\```

**Comment by SPWwj** [comment]
@JasonRay168 Hi, I'm from your senior batch. I've tested the code on my local machine and it runs fine without any `NullPointerException`.

Has your issue already been fixed? If not, it would be helpful if you could provide instructions for us to reproduce the exception.

**Comment by cheeheng** [comment]
Hi @JasonRay168. I am from your senior batch. I have managed to reproduce the error on my system (using Windows) even though the application runs fine. 

I changed the JavaFX version in the build.gradle file to 11.0.2 and the error disappears. I suspect it may be because we are using JavaFX 17 this semester alongside Java 11. I tried upgrading my past iP to JavaFX version 17.0.7 and the same error appears.

**Comment by hansstanley** [comment]
Hi @JasonRay168, another senior here. I see that you've added the `@FXML` annotations, presumably that has fixed the `NullPointerException` errors.

Regarding the warning about the unsupported JavaFX configuration, [this SE-EDU guide](https://se-education.org/guides/tutorials/javaFxPart1.html) states that it can be ignored, so that's the easy way. Here's the relevant section:

![Screenshot 2023-09-10 at 14 22 20](https://github.com/nus-cs2103-AY2324S1/forum/assets/20805849/b610f1e8-8a7c-47f4-96bd-544f84a92605)

If you want to resolve the warning, my understanding from [this](https://stackoverflow.com/questions/67854139/javafx-warning-unsupported-javafx-configuration-classes-were-loaded-from-unna) is that the issue has existed since JavaFX 9 but the warning is only emitted from JavaFX 16 onwards, which explains why using JavaFX 11 triggers no warning. Since the course now uses Java 11 with JavaFX 17, adding the following to your `build.gradle` might help (adapted from [this](https://openjfx.io/openjfx-docs/#gradle), `JavaFX and IntelliJ > Non-modular with Gradle > 2. Modify the build`):

```gradle
javafx {
    version = "17"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```

Just a disclaimer, I use Azul Zulu JDK with JavaFX included so the issue doesn't happen for me, ymmv.
