### ISSUE TITLE
JavaFx: javafx does not exist when compiling files.

### ISSUE THREAD

**Issue by zhanyang01** [nus-cs2103-AY2324S1/forum#128]
Intellij 2023.2, Java 11, Windows

<img width="960" alt="Screenshot 2023-09-09 171858" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/95852686/1f0201ae-fc03-48b5-8380-33a4d78bce3c">
<img width="960" alt="Screenshot 2023-09-09 214244" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/95852686/a0e3a535-4753-4c02-95b3-51844d3cd4b2">
<img width="960" alt="Screenshot 2023-09-09 214417" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/95852686/c943e2e3-f5df-4044-9c66-8cb404215d92">

Compiling the files do not work but using ./gradlew run works, if anyone knows how to fix it please advise.

Thank you.

**Comment by Tim-Siu** [comment]
I think you are supposed to use gradle to build your project instead of using javac.
I am not exactly sure about the underlying principles though.

**Comment by woojiahao** [comment]
Could I ask why you want to compile the files? 

Once you start importing public libraries, it becomes increasingly more challenging to manually compile the code. You do not need to manually compile your Java code with Gradle since it does it for you. That's the whole purpose of using a package management tool instead of manually downloading and managing your dependencies (see CMake and C++ for why this is tedious and painful)

The reason this is failing is because Gradle downloaded the dependencies from the internet and you are not including them when you compile your programs

Edit: manually compiling all the JavaFX dependencies would mean downloading the JAR files and using the following command: https://stackoverflow.com/questions/9395207/how-to-include-jar-files-with-java-file-and-compile-in-command-prompt

**Comment by zhanyang01** [comment]
Hi, I was thinking why i cannot compile my files as I thought it might be easier to debug things if we are able to compile it. 

Thanks for the clarification @woojiahao , @Tim-Siu.
