### ISSUE TITLE
JavaFX Tutorial part 4: Error, Caused by: java.lang.ClassNotFoundException: MainWindow

### ISSUE THREAD

**Issue by yyyaohhh** [nus-cs2103-AY2324S1/forum#132]
Hello, I faced this error when completing the last part of JavaFX Tutorial part 4.
May I know how should I solve it?

<img width="347" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/f931d9de-4a75-4bb0-baa8-1bf595b4753e">

<img width="605" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/e14e396a-ecf0-4486-83b1-d0ea6bffb7f0">

**Comment by jacobcuison** [comment]
Have you updated your `MainWindow.fxml` file? I think the `fx:controller` property of AnchorPane should be updated to something like `fx:controller="duke.MainWindow"`. Hope this helps!

**Comment by yyyaohhh** [comment]
Hi, thanks for your help! It solved that problem but I seem to face a nullPointerException now.
<img width="331" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/963a97ee-77dd-447e-a797-de184de831c8">

**Comment by nixonwidjaja** [comment]
nullPointerException might mean it can't fetch your images

**Comment by kiatkat** [comment]
Agreed, do check both your image references - I had that error and an incorrect filename was the issue.

**Comment by MagnificentCreature** [comment]
I helped a friend with a very niche and difficult issue with nullpointer/failure to load even though my filepath was correct.

I suspect it was because the github code base was in a onedrive folder, and an item in the folder had spaces in it. After many hours I tried moving the whole code to local desktop and without changing any code it worked just like that ¯\_(ツ)_/¯. (It also worked if I moved it to another one drive folder that didn't have spaces in its filepath)

**Comment by damithc** [comment]
@yyyaohhh Perhaps you can push the code to a branch in your fork and share the branch name here so that other can try to replicate the exact problem (or do a more thorough examination of the code).

**Comment by yyyaohhh** [comment]
Thank you guys for the help! I have checked that my image references are correct now, but when I tried sending some text there was a nullPointerException, and I realised that it was unable to load my images properly.
I have pushed my code to the branch "GUI"
<img width="229" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/4bd40b7a-26a2-4469-93d4-4307a1dedb29">
<img width="482" alt="image" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/105197030/988320f4-65ca-4089-a1c6-6522938e36df">

**Comment by axmszr** [comment]
Hi @yyyaohhh! Past student chipping in here.

You may have forgotten to include your /images/ folder. It isn't shown in the GUI branch!

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/72402917/056235ed-588b-4015-8a48-0a6b5611f46d)

(Btw, it may be best to have your package names in lowercase, i.e. `duke` instead of `Duke`)

**Comment by daitenshionyan** [comment]
Hello I am from your senior batch. In [this line](https://github.com/yyyaohhh/ip/blob/79e08b7114145e6cc0ffb0113381c3f3ecd4c5f1/src/main/resources/view/DialogBox.fxml#L8C227-L8C252) of `DialogBox.fxml` there is an additional `fx:controller="DialogBox"`

I was able to resolve the error by removing this additional portion so the line becomes:

```
<fx:root alignment="TOP_RIGHT" maxHeight="1.7976931348623157E308" maxWidth="1.7976931348623157E308" prefWidth="400.0" type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/20.0.1" xmlns:fx="http://javafx.com/fxml/1">
```
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/100074448/713bf195-e8e0-4565-8bb6-f60bfee6a738)

If you would like to edit it in scenebuilder, the field to do so is here:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/100074448/51538bb8-4f7d-48f0-ae11-4527f465bb50)

Leaving it blank should solve it.

This is assuming that the image paths lead to a correct image.

**Comment by jefrai** [comment]
Hello, yet another senior dropping by! I played around with the repo a bit and boiled it down to the same thing as what @daitenshionyan found, so I'll assume that's it.

Just to add in my two cents, the reason why execution failed with a difficult-to-diagnose `null` in `DialogBox.java`
```java
private DialogBox(String text, Image img) {
    try {
        FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);
        fxmlLoader.load();
    } catch (IOException e) {
        e.printStackTrace();
    }

    dialog.setText(text); //null?
    displayPicture.setImage(img);
}
```
was because

1. The extraneous tag in `DialogBox.fxml` causes an exception in `fxmlLoader.load()`
2. The exception is correctly caught and printed to console, _but..._
3. Immediately afterwards, the line `dialog.setText(text)` is run, throwing an uncaught exception and **hiding the above output**.

In terms of code quality, it might therefore have been a good idea to place `dialog.setText(text)` and other set-up within the `try-catch` block - if FXML loading fails due to an implement mistake or in an actual exceptional situation, you want to abort the whole `DialogBox` construction, including those lines, so that the program stands a better chance at failing gracefully.

Alternatively, if you want to keep the `try-catch` block specific to FXML loading, it would be even better to simply add an equivalent `return` guard clause:

```java
...
      fxmlLoader.load();
  } catch (IOException e) {
      e.printStackTrace();
      return;
  }
  
  dialog.setText(text);
...
```

**Comment by cheeheng** [comment]
Hi @yyyaohhh. I am a student from a previous batch. To add on to @axmszr's comment, to prevent accidentally forgetting to track changes of a file in Git, one can use the command `git add .` which adds currently untracked files not ignored by .gitignore to stage for commit, as well as to stage all modified files that are currently tracked by git to commit. The command also makes all currently untracked files not ignored by .gitignore to be tracked in future git operations.

**Comment by muhammadreyaaz** [comment]
Hello another senior from the previous batch again! Since many of the seniors have given you an answer, you might wonder how did they even find that out. Other than using the intellij debugger tool which I highly recommend, we can simply use the intellij auto detector tools to find out if some of the variables or parameters given might cause errors. In this case, when I cloned your GUI branch, in the MainWindow, the fxml class is highlighted in red as seen below.

<img width="1440" alt="Screenshot 2023-09-12 at 8 51 21 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/67105732/f5d8fc91-49fc-4a11-a6dc-d71a3a0cbd93">



If you hover over it, you will get



<img width="1440" alt="Screenshot 2023-09-12 at 8 53 12 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/67105732/ca22537d-3bb0-450f-8dda-ad7537469a7c">


So simply removing it should do the trick :-)

**Comment by daitenshionyan** [comment]
# How problem was determined

If you are curious as to how I was able to determine the error all I did was add an additional print statement in the catch portion of the try block when loading the FXML file.

```java
try {
    FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
    fxmlLoader.setController(this);
    fxmlLoader.setRoot(this);
    fxmlLoader.load();
} catch (IOException e) {
    System.out.println(e); /* Additional statement here */
    e.printStackTrace();
}
```

Doing so will print the main exception and its message (additional line) together with its stacktrack (from `e.printStackTrace()`).

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/100074448/8423041d-a025-4f3b-bd25-61abbf7ad8c0)

The green area is what the additional line prints and was how I was able to quickly determine the issue. The issue being that the controller was set in the FXML file and in code (`fxmlLoader.setController(this)`).

~~Also the fact that I almost punched a hole in the monitor when I first encountered and tried to resolve this error...
I only managed to resolve it that time by redoing (deleting and recreating) the entire thing from scratch and finding that few character difference.~~

# Exception handling

As for exception handling I agree with what @jefrai has. Just I feel that none of the code should be wrapped in any `try` blocks and any exception thrown should be thrown to the caller that is able to handle this exception. If none is able to handle it, then the program should terminate as it is already an indicator that there is a fault in the program. This will print the message of the exception together with the stacktrace without you explicitly stating it. I believe this makes debugging a lot easier.

Here is the version of `DialogBox` constructor for an example of what I mean:

```java
private DialogBox(String text, Image img) throws IOException {
    FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
    fxmlLoader.setController(this);
    fxmlLoader.setRoot(this);
    fxmlLoader.load();

    dialog.setText(text);
    displayPicture.setImage(img);
}
```

# fx:controller in FXML

From the error message, commenting out `fxmlLoader.setController(this)` line should solve the problem but it does not. This is because the controller name should include the package path as well. ie. `fx:controller="Duke.DialogBox"`.

However this does not yet solve the issue. Instead, the exception become `javafx.fxml.LoadException:`. This is because javafx is unable to find the default constructor for `DialogBox` (the constructor that takes no arguments) as a constructor that takes arguments is already declared.

By defining the default constructor, `FXMLLoader` no longer throws an exception but you are still left with the `NullPointerException`. This is because the controller of what `FXMLLoader` has loader is a separate instance of `DialogBox`. Thus the `dialog` and `displayPicture` members of `DialogBox` that you wish to construct is not initialised.

So then how do you set the image and text to what you want when `DialogBox` is being constructed? One way is the following which I highly **DO NOT** advice:

```java
private DialogBox(String text, Image img) {
    try {
        FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
        // fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);
        fxmlLoader.load();
    } catch (IOException e) {
        System.out.println(e); /* Additional statement here */
        e.printStackTrace();
    }

    for (Object o : this.getChildren()) {
        if (o instanceof Label) {
            ((Label) o).setText(text);
        } else if (o instanceof ImageView) {
            ((ImageView) o).setImage(img);
        }
    }
}
```

This code goes against all the "good programming techniques" that we have been taught...

So then what is the use of this `fx:controller` in FXML or doing `fxmlLoader.setController(this)` with an argument other than `this`? I believe it is just to separate the different components. In that way the controller does not need to inherit any javafx classes, thus being its own independent class. I think the structuring theory of this should be covered in class so I have ommited most of the details and technical terms.

**Comment by yyyaohhh** [comment]
Hi seniors! Thank you all for the great step-by-step assistance provided!!! I really appreciate all your help!💕
Thank you all so much for the clear and detailed explanations about debugging and all the advice! I really learnt a lot from yall!👍👍👍
