### ISSUE TITLE
Convention about dependencies when creating unit tests

### ISSUE THREAD

**Issue by elhy1999** [nus-cs2103-AY2324S1/forum#134]
I understand that when we create unit tests for a particular method, we should isolate the method from its dependencies. However, how about the following case:

```
class Foo {
    public Bar fooMethod() {
        return new Bar();
    }
}
```

Here, it seems that it is impossible to isolate `fooMethod` from the `Bar` class as it is supposed to return it. In such cases, can we assume that it is okay not to isolate the two? If so, then wouldn't `fooMethod` depend on the constructor of `Bar` not being buggy? Apologies if this question seems a little silly 😆

**Comment by damithc** [comment]
Good question @elhy1999 Will leave to others to share what they think e.g., _can_ it be done? _should_ it be done? etc.

From an admin POV, the course doesn't require that all unit tests _must_ isolate the SUT. As usual, consider pros/cons and make a decision accordingly.

**Comment by woojiahao** [comment]
I personally do not see an alternative to testing it as is. I view unit testing practices as guidelines that should be done when possible. In this scenario, if you are worried about the reliability of returning the instance `Bar`, then the thing you should focus on is not the fact that there is a dependency, but rather, making sure that `Bar` is properly unit tested separately. This way, you are "guaranteed" that `fooMethod` would not be buggy.

The key here is to make sure `Bar` is independently tested (or as much as it can be) and that way, you are sure there is no issues returning a new instance of it from `Foo`. You shouldn't need to test the `Bar` object returned from `fooMethod` inside `Foo` since then you would have overlapping unit tests. So there's two separate test files, `BarTest` and `FooTest` and you don't mix the unit tests

That's my take on this

**Comment by ghost** [comment]
I agree with @woojiahao about ensuring that `Bar` is properly unit tested separately. One example I can think of is if `Bar` is a `String` so `fooMethod()` will return a `String`. It wouldn't make sense to test how the `String` is being created but rather just assume that its being created correctly. If theres anything wrong with the `String` class creation, it should be caught by the `String` classes unit tests (which i'm sure the people creating the standard Java library have done so).

**Comment by KamJiaYue** [comment]
It seems that you are just trying to test a constructor, instead of testing whether the instance created fulfills any requirements. Test cases like this can only have bugs when Bar is an abstract class, its constructor is private, etc. I think before testing we can ask ourselves "What are we testing for ?", Is it just to check whether that constructor correctly creates that instance for you or any other requirements?

**Comment by elhy1999** [comment]
I see. Thanks to @woojiahao @chiayunrong @KamJiaYue and prof @damithc for your input! I think I have a better idea of how to formulate my unit tests now 😄
