### ISSUE TITLE
Tests pass using CLI but shows Execution failed for task ':test'. when runned on Intellij

### ISSUE THREAD

**Issue by RSXIX** [nus-cs2103-AY2324S1/forum#154]
https://imgur.com/a/SsRFLbh

**Comment by AlagappanRa** [comment]
Attempt these fixes for now: 

Try rebuidling gradle using the gradle refresh icon. 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/118afa52-e41c-433a-ac3e-cf1665f816bf)

Updates:
Could you run with --stacktrace or --info and show us the output.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/534bd4b9-6fde-4888-abed-0d8fea4f77ba)

Modify jvmArgs to '--stacktrace' or '--info' or use the settings given in the image above.

**Comment by RSXIX** [comment]
Hi, I was already rebuilding gradle but it didnt help

I changed my build.gradle as shown but not sure what to do after

Here's the CLI command --stacktrace

https://imgur.com/a/ZjM9uOG


Thank you

**Comment by AlagappanRa** [comment]
Ok, looks like a Intellij environment related problem. 

**Compare environment between terminal and intellij**
Run `./gradelew -g` from the command line to print the environment variables and system properties. Compare this to the environment in Intellij(`Run` > `Edit Configurations` > `Environment variables`) to make sure if they match.

Update it here if possible also!

**Delete all .idea and .iml files**
These files could have become corrupted. Delete them and relaunch Intellij. Intellij should restore those fiiles.

**Comment by damithc** [comment]
> https://imgur.com/a/SsRFLbh

@RSXIX you can paste images/gifs directly in GitHub post. That's more convenient for readers.

**Comment by AlagappanRa** [comment]
If after all that the issue persists you could send the result of running the following as an image.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/a13f4c97-7efd-4751-9faa-1d155ac47412)
Make sure you see under run configurations ip[:test] in your case. Double click to run it.

Attach the screenshot of the run, which looks something like this.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96157054/fac84ea7-5adf-4349-a1eb-b585d81a982b)

**Comment by RSXIX** [comment]
<img width="441" alt="Screenshot 2023-09-20 at 1 38 40 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122437482/ac23bc5a-1934-46ca-aaed-d71c130bb3a7">

I dont even see IP-Test.

Also, the command ./gradelew -g doesnt seem to work

I deleted .idea and ip.iml files and reopened but the same issue persists

**Comment by damithc** [comment]
@RSXIX You can also clone the fork to a different location in your computer and try again, to get a complretely fresh Intellij configuration.

**Comment by AlagappanRa** [comment]
Ok, does this same problem occur with your other test classes such as `Exceptions` or `GUI`? Run them using the Run arrow key on the left of the line index of the editor (like what you did last time with the Event Test)

**Comment by AlagappanRa** [comment]
Actually I think i noticed the culprit. In the image that you attached at the start of the thread, I noticed that you have a `ParserTest` class that is not in a subdirectory of its own. 

You can do following.
1. If your `Parser` class is not in a package, house it under a package. 
2. Then, make sure the test directory follows the **SAME** file structure as your main code. 

I would expect the `ParserTest` to be under a nested directory and not hanging outside by itself, if this is done correctly. 

Reasoning:
Intellij attempts to understand your file structure and generates test build based off its understanding. So, it is highly likely Intellij has misinterpreted your file stucture. As to why your tests run correctly with your `gradelew` command, I think it is because the build was generated before you made some code changes. Those code changes between the last time you built the jar artifact and now is what caused your test to not run correctly in Intellij.

Further help:
Could you share your full test structure if you don't mind? 

Let me know if this helps in any way

**Comment by RSXIX** [comment]
Dear Prof, I will push my code then and clone the fork to another location then.
<img width="257" alt="Screenshot 2023-09-20 at 3 42 35 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122437482/94aa8927-f450-4f7e-add8-66649fdb321b">

As for the test directories, I do think it is in the correct structure. I've provided screenshots.
<img width="288" alt="Screenshot 2023-09-20 at 3 42 55 AM" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/122437482/7700d3ba-1537-4862-8398-e4c9787935a8">

**Comment by AlagappanRa** [comment]
Referring to the image above, `ParserTest` seems to be under package Duke, but from the file structure of your main code, it seems `Parser` is in `main` > `java` > `Duke` > `Tasks` > `Parser`. So I believe the correct test directory should be to move the `ParserTest` into the `Tasks` test directory.

It seems Intellij itself doesn't recognise the test file in this directory, as `ParserTest` is notably highlighted in blue.
