### ISSUE TITLE
Requesting for Linux users for smoke test help

### ISSUE THREAD

**Issue by zacwong2151** [nus-cs2103-AY2324S1/forum#213]
I followed the suggestion on [#173] and now am facing another error, as shown below

![Screenshot 2023-09-24 232024](https://github.com/nus-cs2103-AY2324S1/forum/assets/111118549/c53c12ac-3f04-4c94-a143-750d0867e655)

I'm running on Windows OS and used WSL to switch to Linux environment. As such I'm not sure if this is an issue with my virtual machine or something else. Would appreciate if any Linux users can help me check if my app works. Thanks!

https://github.com/zacwong2151/ip/releases/tag/v0.2

**Comment by Nauxe** [comment]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/51425614/38042bf3-4522-40a5-9ae9-cfa9688b5414)
Works on openSUSE Tumbleweed! 

https://github.com/nus-cs2103-AY2324S1/forum/issues/196#issuecomment-1732597620 suggests that it may not work on your Linux environment because of WSL not supporting GUIs.

**Comment by zacwong2151** [comment]
aight thanks for helping!
