### ISSUE TITLE
Unsuccessful build for github page for ip

### ISSUE THREAD

**Issue by LuoZYi** [nus-cs2103-AY2324S1/forum#226]
![1695903902904](https://github.com/nus-cs2103-AY2324S1/forum/assets/65843388/bd85966f-f956-49e2-b64c-79bae0f6b750)
Experienced this issue when trying to build for github pages for ip. Sorry it's a bit late but anyone can possibly enlighten me on how to resolve this issue? Thanks a lot!!

**Comment by damithc** [comment]
@LuoZYi You seem to be using [Git sub modules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in your repo. Specifically, `src/main/java` folder is configured as a sub module (i.e., it resides as a separate repo elsewhere). You need to remove that and replace the folder with the regular files instead. Otherwise not only CI will fail but also our scripts will have no Java code to grade your iP.

**Comment by LuoZYi** [comment]
> @LuoZYi You seem to be using [Git sub modules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in your repo. Specifically, `src/main/java` folder is configured as a sub module (i.e., it resides as a separate repo elsewhere). You need to remove that and replace the folder with the regular files instead. Otherwise not only CI will fail but also our scripts will have no Java code to grade your iP.

Thank you so much prof! I have now successfully set up the page with your suggestion! I realized that previously I set up the project at the wrong path, i.e. at` src/main/java`, and I think all my branches are also at that folder. Thank you so much prof for your help!
