### ISSUE TITLE
CS2103 Page Down

### ISSUE THREAD

**Issue by Tim-Siu** [nus-cs2103-AY2324S1/forum#231]
<img width="1512" alt="Screenshot 2023-09-30 at 12 47 50" src="https://github.com/nus-cs2103-AY2324S1/forum/assets/61866948/56ff3f5e-9205-4b2a-a866-9afeb3ba86d6">

**Comment by damithc** [comment]
Thanks for reporting this @Tim-Siu Will inform SoC IT.
In the meantime, you can use https://nus-cs2103-ay2324s1.github.io/website/

**Comment by damithc** [comment]
Possibly due to  IT Service Disruption Drill that is going on today (as per the email below).

-------

Dear all,

We would like to remind you about the IT Service Disruption (DR Drill for CR1 COM1) that will take place tomorrow, 30th Sep 2023 Saturday, from 8 am to 5 pm.

Please note that Computer Room 1 will have no power during this period


The affected services are:

1. Network access in CR1

2. Hosted services in CR1

3. UNIX login and file services (e.g. stf, stu)

4. Mail services (e.g. IMAP, mailauth)

5. Print services

6. SoC Compute Cluster

7. Web services

8. Virtual machines (Linux and Windows)

9. Windows login and shared folder services

10. MySoC service
