### ISSUE TITLE
tp dashboard not tracked

### ISSUE THREAD

**Issue by Bryan-Goh** [nus-cs2103-AY2324S1/forum#242]
i closed an issue that was assigned to me with the correct milesrone but still hasnt reflected my progress in the tp dashboard after 2 cycles. its the same thing with the PR that has been merged and assigned to the right milestone also from a branch so i dont know why

**Comment by damithc** [comment]
@Bryan-Goh it's because the name of your team's v1.1 milestone has a leading space i.e., `" v1.1"` which prevented our script from recognizing your issues/PRs as belonging to the right milestone. 
Please ask someone from your team to remove that extra space.
In the meantime, I've tweaked our scripts to ignore such extra spaces. So, your issues/PRs should get detected by the next dashboard update.
