### ISSUE TITLE
Queries regarding user stories

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#246]
I have a few questions regarding user story:

1. Is using a more specific audience in the user story considered missing out on the more general audiences in the user story? For an example, by including only a user story for adding contacts as a salespersons, will this cause us to miss out the important user story of adding contacts as a normal user?
2. Is writing user stories on same feature, but different target users considered duplicate user stories and is it acceptable?

**Comment by damithc** [comment]
Good questions @yucongkoo In general, keep the objective in view so that the mechanism doesn't get in the way of achieving the objective.

> * Is using a more specific audience in the user story considered missing out on the more general audiences in the user story? For an example, by including only a user story for adding contacts as a salespersons, will this cause us to miss out the important user story of adding contacts as a normal user?
> * Is writing user stories on same feature, but different target users considered duplicate user stories and is it acceptable?

Ensure your target user, whoever that is, is covered by your user stories. If your app is for sales people, it is fine not to have user stories for 'normal' people. However, if a specific type of sales people have specific needs (e.g., those selling to companies rather than individuals), you can capture them as separate user stories.

A user story is duplicate if it doesn't capture anything extra that is not captured by other user stories. Consider the following:
A. `As a new user, I can add a contact` 
B. `As an experienced user, I can add a contact` 
The above two can be considered duplicates  (might as well use `As a user, I can add a contact` instead)

However, the below two are not duplicates.
C. `As a user, I can add a contact` 
D. `As a new user, I can add a contact interactively, so that I can get used to the command syntax incrementally` 
Furthermore, it's not enough to have D only (without C) as it doesn't cover needs of not-new users.

**Comment by yucongkoo** [comment]
I see, understood. Thank you prof!
