### ISSUE TITLE
Is mid-v1.2 a hard deadline?

### ISSUE THREAD

**Issue by juliusgambe** [nus-cs2103-AY2324S1/forum#251]
All our team members have more than 2 midterms this week and we realise that we would be unable to complete the mid-v1.2 iteration before the tutorial or even before the lecture. We are worried we may be penalised and at the same time, we also do not want to produce low quality work to try meet the deadline. May we know if there are any penalties if we are unable to complete the deliverables before tutorial and lecture? Or are we able to complete by Sunday?

**Comment by damithc** [comment]
@juliusgambe We strongly _recommend_ splitting this iteration into two increments v1.2 and v1.2b, and finishing the first increment this week. The usual hard deadline for weekly tasks (i.e., lecture) seems like a good target to go for but it is up to you (it is an _internal_ deadline that you set your self). 
It is also not unexpected for some teams to overshoot your first few deadlines, as it is hard to estimate how much effort the work will take at first. In fact that is why we recommend splitting into smaller iterations so that you have more chances to calibrate your iteration planning (e.g., how much work to allocate to an iteration) by trial-and-error. Accordingly, we don't penalize for overshooting these initial deadlines -- because it is unreasonable to fault you for not having the exact skill you are trying to learn.
