### ISSUE TITLE
Specifying name for objects in UML Object Diagram

### ISSUE THREAD

**Issue by tim-pipi** [nus-cs2103-AY2324S1/forum#252]
During the tutorial (week 8), it was mentioned that you can technically put any name before the `:ClassName` in an Object Diagram if the object was unnamed. For example, for the `StockItem` example in Week 8 tutorial, you could put `:StockItem` or `s:StockItem` or `spanner:StockItem` - all of these are valid.

However, in the case for an object that is already given a name, for example:
`StockItem stock = new StockItem("spanner", Rating.POOR)`

Would it still be possible to name it with anything other than `stock:StockItem` or `:StockItem` ?

**Comment by damithc** [comment]
@tim-pipi Good question. 
In the example `StockItem stock = new StockItem("spanner", Rating.POOR)`, `stock` is the variable name, not technically the object name. The variable can point to different objects at different times, and it could be confusing if all those objects were given the same name. That said, it makes sense to use the same variable name for the object when it doesn't lead to such confusion, rather than introduce yet another name into the diagram.

**Comment by tim-pipi** [comment]
Thanks Prof!
