### ISSUE TITLE
Java CI Test Failed, Gradle Test Passed Locally 

### ISSUE THREAD

**Issue by WeeeHung** [nus-cs2103-AY2324S1/forum#253]
Prior to pushing new commits to the [pull request](https://github.com/AY2324S1-CS2103T-T14-3/tp/pull/63), I did Gradle Test locally in my Intellij (Windows) using  `./gradlew clean test`. It passed all cases and showed the following.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/96626287/508932c5-d926-426e-9112-440b9e53b09a)

Nonetheless, after I push these commits, it failed all Java CI Checks initially (ie. for ubuntu, macos, windows).
I then rerun the Java CI Check twice without pushing new commits as I was sure that the 5 errors shown were fixed, and this time ubuntu and windows managed to pass the CI Test.

However, the Java CI Check for Macos still did not pass and is now showing the same 5 errors as mentioned earlier. The mentioned errors can be found in this [GitHub Actions Log](https://github.com/AY2324S1-CS2103T-T14-3/tp/actions/runs/6495863766/job/17641639876?pr=63).

Group members with different OS (ie. Macos and ubuntu) have tried running gradle test locally and passed all cases as well. 
How else should I be debugging this or is it a GIthub Actions/ Java CI issue?

**Comment by damithc** [comment]
@WeeeHung While waiting for others to chime in, you can try rerunning CI a few more times to see if some pattern emerges or if it is totally random.

**Comment by WZWren** [comment]
I am part of @WeeeHung's team, and I wanted to update that we have been rerunning CI a few times already, and only the runner on macOS seems to encounter this issue. The error was always caused by a `JsonMappingException` from the `fasterxml` library, but we are unable to trace the error as we can't access the error log on the runner in the workflow.

**Comment by oeggy03** [comment]
Instead of running `gradlew clean test`, you can run `gradlew clean build`, and see if it tells you any more useful info

Also, you can trying rolling back or upgrading the version of fasterxml/jackson databind in dependencies of your build.gradle to see if it works. Currently it's 

```
 implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.7.0'
 implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.7.4'
```

https://github.com/FasterXML/jackson-databind you can refer to this and try one of the newer versions. Seems like 2.7.0 was quite a while ago

Just throwing ideas I too am confused. But my best guess is that the version of fasterxml you have in your project isn't stable for mac specifically somehow

**Comment by WeeeHung** [comment]
Thank you for the idea. I have tried rolling back and upgrading to a number of versions. Both did not work. For upgrading specifically, it introduced a new [issue](https://github.com/FasterXML/jackson-databind/issues/1422), where relative paths are deserialised into absolute paths, causing some assertions to fail. 

ie.
`org.opentest4j.AssertionFailedError: expected: <seedu.address.commons.core.Config{logLevel=INFO, userPrefsFilePath=preferences.json}> but was: <seedu.address.commons.core.Config{logLevel=INFO, userPrefsFilePath=C:\CS2103T\tp\preferences.json}>
`

With regards to the pattern,
> @WeeeHung While waiting for others to chime in, you can try rerunning CI a few more times to see if some pattern emerges or if it is totally random.

I just found it strange that sometimes the Java CI check fails on Windows and Ubuntu with the same errors as macos, but this get fixed after rerunning. I guess the only pattern here is rerunning works for Windows and Ubuntu.

**Comment by damithc** [comment]
@WeeeHung Another general debugging technique you can use (to locate the problem code) is to create a new PR and incrementally add the changes in this PR to the new PR, to figure out precisely which part of the code is causing this problem.

On a related note, it is best if upgrading of dependencies (e.g., JavaFX version, JUnit version) are done in separate PRs so that their effect can be isolated, and they are easier to roll back later (should the need arise).

**Comment by WeeeHung** [comment]
Thank you so much prof, we have just figured out the issue and all OS is now passing the CI Check.

The problem was with the overloaded JsonAdaptedPerson Constructor that we have created. We overloaded the constructor because we added new fields to Person Constructor but have yet to make corresponding changes in Test folder. As a result of this overloaded constructor, Windows OS occasionally fails and Macos always fails potentially due to how they interact with the JsonCreator and JsonProperty.

Before
```
@JsonCreator
public JsonAdaptedPerson(@JsonProperty("name") String name, @JsonProperty("nric") String nric,
                             @JsonProperty("phone") String phone, @JsonProperty("email") String email,
                             @JsonProperty("address") String address, @JsonProperty("appointment") String appointment,
                             @JsonProperty("medicalHistories") List<JsonAdaptedMedicalHistory> medicalHistories,
            @JsonProperty("tags") List<JsonAdaptedTag> tags) 
            
public JsonAdaptedPerson(@JsonProperty("name") String name,
                             @JsonProperty("phone") String phone, @JsonProperty("email") String email,
                             @JsonProperty("address") String address,
                             @JsonProperty("tags") List<JsonAdaptedTag> tags) {
```

After
```
@JsonCreator
public JsonAdaptedPerson(@JsonProperty("name") String name, @JsonProperty("nric") String nric,
                             @JsonProperty("phone") String phone, @JsonProperty("email") String email,
                             @JsonProperty("address") String address, @JsonProperty("appointment") String appointment,
                             @JsonProperty("medicalHistories") List<JsonAdaptedMedicalHistory> medicalHistories,
            @JsonProperty("tags") List<JsonAdaptedTag> tags) 
            
public JsonAdaptedPerson(String name,
                             String phone, String email,
                             String address,
                             List<JsonAdaptedTag> tags) {
```

Thank you all for the debugging suggestions. Credits @WZWren
