### ISSUE TITLE
IP Level-4 question

### ISSUE THREAD

**Issue by Song-Mengfei** [nus-cs2103-AY2324S1/forum#3]
Based on the requirements of Level-4 and Level-5, can I state that tasks could only be added by using key words "todo," "deadline," and "event"?
If not, how can I distinguish between adding a new task and invalid input?

**Comment by damithc** [comment]
> Based on the requirements of Level-4 and Level-5, can I state that tasks could only be added by using key words "todo," "deadline," and "event"?

@Song-Mengfei Yes, that's fine.

**Comment by Song-Mengfei** [comment]
Thanks!

**Comment by lhy-hoyin** [comment]
Hello @Song-Mengfei
It looks like your issue has been resolved. If that is the case, perhaps you can close this issue. Otherwise, perhaps you can elaborate on what you still wish to clarify.

Also, I noticed that your issue description seems rather generic. If possible, I would suggest giving a more informative issue title in the future. ( eg. IP Level-4 use keyword only message) A more informative title is better especially in the later weeks where there are are lot more open issues.
