### ISSUE TITLE
How can we have an overview of code contributed by us

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#308]
I am wondering whether do we have a way to have an overview of all the codes we have contributed to the team repo so that we can catch possible code quality violations. I was playing around with the TP code dashboard but couldn't actually find the way to achieve this.

**Comment by damithc** [comment]
@yucongkoo do you mean you want to see all code an individual contributed to the tP?

**Comment by yucongkoo** [comment]
@damithc Yes prof, specifically see all the code I contributed to the tP.

**Comment by damithc** [comment]
@yucongkoo You mean other than clicking the `</>` icon near your name (which should give you [this view](https://nus-cs2103-ay2324s1.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code&since=2023-09-22&tabOpen=true&tabType=authorship&tabAuthor=yucongkoo&tabRepo=AY2324S1-CS2103T-W16-2%2Ftp%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=docs~functional-code~test-code&authorshipIsBinaryFileTypeChecked=false&authorshipIsIgnoredFilesChecked=false))?

**Comment by yucongkoo** [comment]
@damithc Ahh I got the wrong icon, sorry for any inconvenience caused. Thanks prof.
