### ISSUE TITLE
Is this considered a feature flaw or bug?

### ISSUE THREAD

**Issue by TehOPanas** [nus-cs2103-AY2324S1/forum#332]
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/2e037d2b-81bc-4195-a476-e29bb3c02938)

Regarding the screenshot above, given that I did not allow all types of 8 digits to work, even though I have specified that it does, Is this considered a functionality bug or feature flaw ?

**Comment by damithc** [comment]
@TehOPanas can you share the corresponding UG (i.e., version as at PE-D) section that describes the expectations for this parameter?

**Comment by TehOPanas** [comment]
here you go 

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/111107699/5f000969-f48d-4243-b679-95c64ff8782d)

**Comment by damithc** [comment]
@TehOPanas Based on this (given there is no specific mention that spaces in the middle are allowed), allowing spaces seem like an enhancement that wasn't considered while implementing this feature earlier. So, adding it now will not be allowed but you may,
1. revise the UG to specify the current behavior more clearly/precisely
2. list this enhancement under 'Planned enhancements' section so that it will not be penalized in the PE.

**Comment by TehOPanas** [comment]
Got it, thanks prof
