### ISSUE TITLE
Question regarding definition of missing important user stories

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#343]
As stated in the website, missing important user stories is considered a DG bug, but how do we actually define `important user stories`? Are user stories that fall under the scope of project constraints(e.g. fast typist, CLI etc) considered important user stories?

**Comment by damithc** [comment]
@yucongkoo While it is not possible to define this objectively, we can consider the following as _important_ user stories:
* Those that are must-have for the application to be any use at all
* Those corresponding to features that are already implemented 
* Those corresponding to features that are stated as planned in near future (in the UG or the DG)
* Those necessary for the app to be reasonably useful for target users

Project constraints are a better fit for the NFRs section rather than user stories.

**Comment by yucongkoo** [comment]
@damithc Ahh I see, thank you prof.
