### ISSUE TITLE
Questions about bug fixes and feature enhancements

### ISSUE THREAD

**Issue by A1WAYSD** [nus-cs2103-AY2324S1/forum#351]
Hi Prof, can we check if we are allowed to do the following fixing in v1.4:

Here's our previous GUI:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/112334419/7b1c922a-d1ed-4245-ac58-9b5932106ea0)

[Issue](https://github.com/AY2324S1-CS2103T-T11-4/tp/issues/260) reported in PE-D: 
Users are not able to differentiate translations with different languages. This is unreasonable in real world and considered a FeatureFlaw bug.

Current solution to fix this issue: Adding a language tag to allow users to have ways to see and check the translation language.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/112334419/95458ea6-d0b7-44f8-9f7b-f44e866c88c6)

Our purpose is purely to resolve this product design issue and that we found adding the language tag is the most suitable and intuitive way for us to fix it. Thank you!

**Comment by damithc** [comment]
@A1WAYSD This sounds like a quality-of-life improvement for users, rather than a bug fix (i.e., the tester was correct to categorize it as a FeatureFlaw). So, this can be a _planned enhancement_ but not allowed to implement during the feature freeze (as fixing FeatureFlaws is not allowed during feature freeze).

**Comment by Tim-Siu** [comment]
This is interesting. It seems like it doesn't fall into the 'bug' category since it doesn't differ from the advertised behavior, nor does it fit into the 'feature change' category since there is no workaround. Let's see what the professor will say.

_On a side note, I am here partly to secure some participation points :)_

**Comment by A1WAYSD** [comment]
Thank you Prof for clarifying and the suggestions for adding to planned enhancement!
