### ISSUE TITLE
Changing error messages in implementation to match UG

### ISSUE THREAD

**Issue by keaganpzh** [nus-cs2103-AY2324S1/forum#352]
Suppose my UG states that the error message for a wrong command is `message A`. Currently, when said wrong command is inputted into the app, `message B` is shown to the user instead.

`message B` is not wrong per se, but it is too general. I understand that if a message is too general, it is not considered a bug. However, since there is a discrepancy between what the app shows and the expected outcome in the UG, is this considered a bug? And are we able to fix the error message in the implementation to match `message A` in the UG?

Thank you.

**Comment by damithc** [comment]
@keaganpzh if the UG specifically states one error message but the actual app gives out another error message, there are two possibilities:
(a) it is something you intended to implement but never got around to it, or,
(b) you implemented it but it is not working correctly due to some error in the code (e.g., the logic to decide/generate the correct error message is already in the code but not wired up correctly to the right place). 

If it is the former, you should change the UG to match the current behavior (to minimize changes to the code). 
If it is the latter, you can fix it.

**Comment by keaganpzh** [comment]
Thanks for the clarification!
