### ISSUE TITLE
Is encryption of addressbook.json file allowed?

### ISSUE THREAD

**Issue by ryanongwx** [nus-cs2103-AY2324S1/forum#355]
I have implemented an encryption function in my team's team repository such that the addressbook.json file s encrypted

This is to ensure any unauthorised usage of the application will not be able to view the data. This is because our application is targeting doctors and it stores confidential patient data.

According to the constraints of the team project, advanced users will still be able to use make edits to the addressbook.json by encrypting and decrypting the file.

Is encryption of addressbook.json file allowed?

**Comment by damithc** [comment]
@ryanongwx this feature can co-exist with the said constraint, provided there is a feature for the user to decrypt the file, and another feature to encrypt it again after editing it manually. Otherwise it is a violation of the constraint.

**Comment by ryanongwx** [comment]
@damithc We do not provide that feature as it defeats the purpose of having an encryption feature. We have included an online encryption/decryption tool which advanced users (with the secret key) can used to decrypt the file and encrypt it again after editing it manually.

Is that a violation of the constraint?

**Comment by damithc** [comment]
@ryanongwx Yes, it will be considered a violation of the constraint. In particular, PE testers allocated to test your app will be unfairly inconvenienced due to this feature.

Your options:
1. Disable the encryption feature (feature removal is allowed during the feature freeze)
2. Leave it in, but if a PE tester reports this, accept it as a FeatureFlaw type bug
