### ISSUE TITLE
Determining if this is a bug or feature flaw

### ISSUE THREAD

**Issue by techjay-c** [nus-cs2103-AY2324S1/forum#358]
Hi, for context, our app ToothTracker allows patient and dentist records to be added. However, it is highlighed by one of the testers during PE-D that our app cannot handle records with the same name. eg there can only be 1 "John" in the system, or "John Tan" in the system. Are we allowed to fix this and handle duplicate records to be more like how in the real world it is, where a dental clinic management system will likely have multiple records with the same name, but differing attributes such as phone number and address?

If we are not allowed to fix this, will we me marked down during the final PE?

Thank you.

**Comment by damithc** [comment]
@techjay-c This is a flaw in the feature design rather than a bug in the implementation. For now, you can explain a workaround in the UG e.g., if multiple people have the same name, add a unique suffix to the name to differentiate (e.g., last N digits of the IC number) `John Tan (34H)`. Updating the behavior to handle this in a better way can be a future enhancement.

**Comment by techjay-c** [comment]
Thank you prof
