### ISSUE TITLE
LinkageError occurred while loading main class duke.Duke

### ISSUE THREAD

**Issue by TiwKangXu** [nus-cs2103-AY2324S1/forum#36]
Error "LinkageError occurred while loading main class duke.Duke" when trying to run Duke.java after building JAR File. Steps to reproduce error:
1. Complete all tasks before A-Jar.
2. Complete A-Jar using _With Gradle_ method. * Edit line 31 in build.gradle, from _mainClass.set("seedu.duke.Duke")_ to _mainClass.set("duke.Duke")_
3. Navigate to build.libs and run _java -jar duke.jar_. duke.jar executes successfully.
4. Navigate to Duke.java in IntelliJ and run. Error occurs.

Thanks in advance.

**Comment by geraldngjx** [comment]
Hi @TiwKangXu ,

This is what I have gathered from my experience and from web resources such as StackOverflow based on the information provided in the issue that you have raised.

The error is likely occurring because of a discrepancy in the package name used in the mainClass configuration in your build.gradle file and the actual package name in your code. You may try to go through the following steps to fix the problem:

Update build.gradle:
In your build.gradle file, make sure that you have the correct package name set for the mainClass configuration. Since you mentioned that you changed it to duke.Duke (line 31 in build.gradle), make sure it matches the package name of your Duke.java class.

My file structure is as follows: src > java > main > geraldbot > Duke.java. The following is the way that I have configured my mainClass in build.gradle:

application {
    mainClassName("geraldbot/Duke")
}

Rebuild JAR:
After making sure that the package names are consistent, rebuild the JAR using Gradle to ensure the changes are reflected in the JAR file.  Afterwards, run the jar file to ensure that the JAR is built correctly with the updated package configuration.

After carrying out these steps, open Duke.java in IntelliJ and run it. Since you've updated the package name in both the build.gradle configuration and the source code, you should no longer encounter the LinkageError when running the program within the IDE. Hope this helps.

**Comment by inezkok** [comment]
Hi @TiwKangXu ,

I agree with @geraldngjx that I think the issue leading to this error might be that your main class name in build.gradle and your actual package name in your code.

For me, my Duke.java is located such that: src > main > java > duke > Duke.java. Therefore, my build.gradle looks like:

application {
mainClass.set("duke.Duke")
}

You can just clean your build using gradle and rename your mainClass or package name to make them consistent, before repeating the steps for A-Jar using gradle.

**Comment by TiwKangXu** [comment]
Hi @geraldngjx @inezkok ,

I have realised the source of error. It was due to a Java Version mismatch error. Thank you.

**Comment by SungMatt** [comment]
With regards to this -- is Duke only supposed to run when using the Gradle "run" script now? When I directly run Duke via Duke.java, I get a LinkageError.

**Comment by damithc** [comment]
@SungMatt 

> With regards to this -- is Duke only supposed to run when using the Gradle "run" script now? When I directly run Duke via Duke.java, I get a LinkageError.

'Directly run' how? If you mean run in Intellij, you can try the following two common remedies:
  * Choose File -> Invalidate caches
  * Close Intellij -> Delete the .idea folder -> Re import the project
