### ISSUE TITLE
PE-D Feature Flaw

### ISSUE THREAD

**Issue by Nid21cs** [nus-cs2103-AY2324S1/forum#362]
We received a feature flaw stating that tasks can be marked and unmarked infinitely, e.g. a marked task can keep getting marked. It does not affect functionality at all and was wondering if we can count it as a invalid bug report.

**Comment by damithc** [comment]
@Nid21cs There are several different things to note.
1. This is a feature flaw, not a bug. So, this behavior is not allowed to be changed in v1.4, as per the feature freeze
2. When processing PE-D bugs, you are at liberty to categorized them any way (e.g., invalid, or valid but will not be fixed in v1.4)
3. Other things you can do regarding this, at your discretion: update the UG to explain this behavior clearly to the user; list it under planned enhancement (i.e., if you think the behavior has room to improve). 
4. If the same bug is reported in the PE, you can choose the severity/type/response you think that fits it best, and explain your choice. If the tester agrees with your choice, we go by the selected severity/type/response. If the tester doesn't agree, the teaching team will have to choose whose position is more appropriate i.e., the team's or the tester's

**Comment by Nid21cs** [comment]
Thank you prof.
