### ISSUE TITLE
How to resolve table of contents problem for markbind

### ISSUE THREAD

**Issue by ItsTYtan** [nus-cs2103-AY2324S1/forum#384]
Hi profs and TAs, our team has a problem, markbind produces two table of contents for the pdf conversion. Is there a way to work around this? Thanks!

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/100292419/b654070a-6797-4e49-93bc-f933bbf8501a)

**Comment by damithc** [comment]
@ItsTYtan There is no need to hand-code a ToC, as MarkBind automatically uses the page navigation menu (on the right of the page) as the ToC in the generated PDF.

Let me check if there is a way to replace that with your own hand-coded ToC.

**Comment by damithc** [comment]
@ItsTYtan Actually, is there a need to insert a hand-coded ToC, as there is page navigation menu in the page (on the right) that serves the same purpose?

**Comment by tlylt** [comment]
Hi @ItsTYtan , simply remove the page-nav-print in ur userguide.md and devguide.md

![IMG_2158](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/df94932c-c0fc-4d6a-a1e2-c646338e93eb)

**Comment by craigtonlian** [comment]
I think the `page-nav` menu that gets embedded in the print file only includes up to level 3 headers. So if you prefer for the deeper nested headers to be included in the ToC, might have to go down the manual ToC route. 

I tried editing the `site.json` to include more header levels but could not get it to work.

**Comment by tlylt** [comment]
Hi @craigtonlian, the page-nav does support more than 3 levels of headings, but it has to be the same as the page navigation menu appearing on the right-hand-side. If it's set to level 4 for the page navigation menu, then the printed one will show up as such.

What you need to do is to change `pageNav` in frontmatter of the page to `4`. E.g.
```
<frontmatter>
  layout: default.md
  title: "User Guide"
  pageNav: 4
  pageNavTitle: "Table Of Content"
</frontmatter>
```

It could be that you tried changing the site.json but since pageNav is set to `3` in the .md file itself, the overall logic is to follow the level defined within the page.

Here's an example output:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/42c21d8b-0fb8-486b-ab41-a0c331e43bc3)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/2cc779df-0caa-44da-a98d-2f958371a8e5)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/41845017/28b0dfb2-6d56-491b-9eb7-b440cecfd52b)


More details available at https://markbind.org/userGuide/components/navigation.html#page-navigation-menus

**Comment by craigtonlian** [comment]
Thanks @tlylt ! Doing God's work! 👼

**Comment by ItsTYtan** [comment]
Thank you for all the help, we have managed to resolve the issue with your help :D.

**Comment by adhigop13** [comment]
Thanks for this solution. Our team also had this issue which has been solved now with your help!
