### ISSUE TITLE
Contribution not reflected in the tp Dashboard

### ISSUE THREAD

**Issue by Tang-Moyan** [nus-cs2103-AY2324S1/forum#392]
Hello Prof. In the beginning of our tp, I have defined the overall data structure and basic class which my teammates modified later on. However, some of the files I contributed were moved to other directories by other teammates (copy and paste to the new directory and delete the old one) during our production and my contribution for that part is completely gone (not reflected in the tp Dashboard).

In addition, our team produced the User stories in a google doc first and one of us put them in DG which results in that none of the others have contributions to User Stories reflected in the tp Dashboard.

When we divide jobs, one of us is fully responsible for the demo video production (becuase he is the only one who is familiar with video editing) and others work on UG and DG. So how can the demo video be compared to the contributions in UG and DG?

How will these affect our grade and what should we do about it?

**Comment by damithc** [comment]
@Tang-Moyan 

If needed, you can override the LoC attribution using @@author tags, as explained [here](https://nus-cs2103-ay2324s1.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking).

As mentioned at various points before, everyone needs to do some work in UG, DG, testing, etc. because these things are evaluated separately, testing for different things. For example, if a person doesn't contribute to the DG, we will not be able to assess their DG skills (e.g., UML modelling skills).

On CS2103/T side, the demo video is not graded, and there is no need to do any video editing. Just do a Zoom meeting and record the meeting. No special skills required.

**Comment by Tang-Moyan** [comment]
Sure. thank you prof.
