### ISSUE TITLE
Questions on acceptable bug fixes

### ISSUE THREAD

**Issue by LHeng1** [nus-cs2103-AY2324S1/forum#397]
Hi! Our team wanted to check if fixing the following issues would be acceptable as a bug fix: 
1. One of our commands is not working at all (due to a minor fxid naming error), even though we have the full implementation.
2. Accepting invalid inputs (eg. all numbers as a name).
3. Display bugs (`clear` command leaves details on the screen, name of data file that is displayed in the UI is incorrect).

Thank you!

**Comment by damithc** [comment]
> * One of our commands is not working at all (due to a minor fxid naming error), even though we have the full implementation.

@LHeng1 you can create a PR for this and send me the link so that I can see the extent of this change.

> * Accepting invalid inputs (eg. all numbers as a name).

The following applies:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/3cac8b4a-0631-4345-a18f-8098df103eca)

So, if the user enters numbers as a name, it is not 'incorrect' to accept it, although the behavior can possibly be enhanced (not allowed during feature freeze).

> * `clear` command leaves details on the screen

Can fix.

> name of data file that is displayed in the UI is incorrect).

Can fix.

**Comment by LHeng1** [comment]
@damithc Here is the [PR](https://github.com/AY2324S1-CS2103T-W10-1/tp/pull/180) for fixing the command.

**Comment by damithc** [comment]
> Here is the [PR](https://github.com/AY2324S1-CS2103T-W10-1/tp/pull/180) for fixing the command.

@LHeng1 You can go ahead with the fix.

**Comment by LHeng1** [comment]
Alright, thanks prof!
