### ISSUE TITLE
Question regarding simplicity of sequence diagrams

### ISSUE THREAD

**Issue by seantehds** [nus-cs2103-AY2324S1/forum#398]
Hi Professor!

I am writing this question to clarify what objects need to be included within a sequence diagram.

From the module website, it states that we should keep our diagrams simple.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94635140/2110d426-06ee-46c6-99c2-c12f45709a74)

I would just like to clarify the third point within this image shown above. If I am making a sequence diagram for the command that handles the addition of new objects into the Model component,

1) Is it a necessity to show the initialization of the object?? Or does it fall under the Model component, and that we should not be mentioning the initialized object?

2) If we do mention the initialized object, should we creating the instance within the Logic box or the Model box? I understand that the object is initialized when the `execute` function of the command is being called, which is under the Logic box, but it is an object that belongs to the Model package. Thus should it be under the Model or Logic box?

Thank you in advance for answering my question professor! I really appreciate it!

**Comment by damithc** [comment]
@seantehds Can you give the diagram (or alternative diagrams) for better context?

As to which box should have the object creation, you can go by where in code the corresponding `new` is located.

**Comment by seantehds** [comment]
Hi Professor!

Thank you for your quick reply so late at night!

Within this diagram, should we keep it like this, where we do not have an object initialized:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94635140/d020c103-2000-42c2-bb67-a9e9ce804521)

Or do we have to initialize the object:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94635140/1f98d354-3d0b-4298-a78c-958d827ca8ab)

**Comment by damithc** [comment]
@seantehds As the object added is created inside the Logic component (i.e., by the Parser), it should appear inside the Logic component (i.e., similar to the second diagram)

**Comment by seantehds** [comment]
Could I clarify whether the initialization of the Object is necessary or not? From the website,

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94635140/83139d31-ed12-4271-9232-04bffb291ad4)

No Person object is shown in this diagram. Is this because in this case (for DeleteCommand), the Person is already within the model, and as such it does not need to be shown explicitly to simplify the diagram, while for this case (AddCommand), as a new Object is being initialized and added to the Model, it needs to be explicitly initialized within the Logic component and be passed as an argument via the addPerson command into the Model?

**Comment by damithc** [comment]
**The diagram for the `delete` command:**

>![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/94635140/83139d31-ed12-4271-9232-04bffb291ad4)

This AB3 diagram shows that Logic calls  `deletePerson(1)` on the Model API to delete the person at position 1 -- nice and clean. When looking at the code though, it appears the reality is uglier. The actual deletion is achieved through several interactions with the Model API. Ideally, the step 3 of the explanation below the diagram should mention this simplification in the diagram, so that the reader is aware the actual implementation is more complex than what the diagram shows.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/33379532-e2f9-49d4-bb33-a0d0befa3625)

**The diagram for the `add` command:**

> Could I clarify whether the initialization of the Object is necessary or not?

You can either show the object creation in the diagram, or omit it from the diagram but mention the omission in the explanation, similar to what I suggested above for the `delete` command. Personally, I lean towards the former, as it doesn't complicate the diagram that much but gives a more sincere representation of the actual interaction.

**Comment by seantehds** [comment]
Okay sure, I understand now. Thanks Prof!
