### ISSUE TITLE
Clarification of feature freeze rules and bugs that can be fixed

### ISSUE THREAD

**Issue by mfjkri** [nus-cs2103-AY2324S1/forum#405]
Hi prof, my team and I would like to be very sure we aren't violating any feature freeze rules. Could you help to verify if any of these are violations?

### 1. Parsing and display of year 0000
We have a datetime input and when user inputs year 0000, it is displayed as 0001. 
We have fixed this to display 0000 correctly.

### 2. Unmark accepting multiple m/
We have an unmark command that is supposed to accept just 1 m/ tag. It accepted multiple and we have since restricted it to only 1.

### 3. Theme command ignoring multiple keywords
We have a theme command that is supposed to change the theme by accepting 1 NEWTHEME field. It accepted multiple and took the first word to change. (e.g. theme dark blue was interpreted as theme dark, instead of its intended error)

### 4. Status lost on tutor edit
Editing a tutor caused its associated schedule's statuses to be lost. We have since updated how the command works.

### 5. Calendar schedule being truncated 
We have a `show` command that would display the schedules in a calendar view.
However for schedules with a short duration (under 45 mins etc), it truncate the schedule’s text due to insufficient width of the schedule box to the extent that none of the words are readable.
Despite this the user can still retrieve the schedule information using the `list-s` schedule command which would display all the added schedules in a list.

We have modified the calendar schedule to not display any text entirely except the index for schedules under 45 mins (this prevents the truncation from occurring in the first place).

### 6. Long fields truncated (schedule n tutors)
We modified the UI view of AB-3 to prevent truncation of long fields with the use of a  horizontal scroll.
However this truncation only occurs for “extreme” inputs (names made up of 40 characters of W character etc) and the truncated field can stilll be viewed by the user in full, by resizing the app window manually (for really long names this can take a while).

### 7. Update schedules ordering when day passed 
We have this feature where the product would sort and separate schedules added by the user into two categories:

- Upcoming schedules (including ones that occur on current date)
- Past schedules (those that occured before the current date)

Currently when the day has passed (date changes to the next day’s date), using of any of the commands does not update the schedules order (move schedules that have occured on that given date to past schedules).
The only way to force this update is to make an edit to a schedule which will update the filtered list of schedules and hence causing a UI update.

We have modified all schedule commands to always sort the list when executed.

### 8. Malformed json causing app to crash
It was stated in the FAQ of feature freeze that the app should support manual edits to the json file. We have updated the product to meet that level of support.

However we did not include the section on support for manual edits to the json file like AB3 did.

### 9. Parsing an Index with a number that is too large returns wrong error message
When parsing a command that uses an index as a parameter, if the index provided is too large (e.g. 99999999999), the parser fails to parse it as an integer and treats it as an invalid parameter and returns an `Invalid command format` error instead of `Invalid index`.

Are we allowed to modify this behaviour to return the correct message by checking if the input is made entirely of numbers before trying to parse as an integer?

Thanks!

**Comment by damithc** [comment]
@mfjkri Some are OK, some are not. See below.

> ### 1. Parsing and display of year 0000
> We have a datetime input and when user inputs year 0000, it is displayed as 0001. We have fixed this to display 0000 correctly.

OK

> ### 2. Unmark accepting multiple m/
> We have an unmark command that is supposed to accept just 1 m/ tag. It accepted multiple and we have since restricted it to only 1.

Only if multiple m/ causes the application to misbehave (i.e., crash, give incorrect results, or hinder normal usage). If the application gives the same (or similar) behavior with multiple m/ as it would with a single m/, the behavior is not incorrect (just more forgiving).

> ### 3. Theme command ignoring multiple keywords
> We have a theme command that is supposed to change the theme by accepting 1 NEWTHEME field. It accepted multiple and took the first word to change. (e.g. theme dark blue was interpreted as theme dark, instead of its intended error)

Same as above. You can mention in the UG that it takes the first word and ignores the rest.

> ### 4. Status lost on tutor edit
> Editing a tutor caused its associated schedule's statuses to be lost. We have since updated how the command works.

OK.

> ### 5. Calendar schedule being truncated
> We have a `show` command that would display the schedules in a calendar view. However for schedules with a short duration (under 45 mins etc), it truncate the schedule’s text due to insufficient width of the schedule box to the extent that none of the words are readable. Despite this the user can still retrieve the schedule information using the `list-s` schedule command which would display all the added schedules in a list.
> 
> We have modified the calendar schedule to not display any text entirely except the index for schedules under 45 mins (this prevents the truncation from occurring in the first place).

Seems like an enhancement rather than a bug fix.

> ### 6. Long fields truncated (schedule n tutors)
> We modified the UI view of AB-3 to prevent truncation of long fields with the use of a horizontal scroll. However this truncation only occurs for “extreme” inputs (names made up of 40 characters of W character etc) and the truncated field can stilll be viewed by the user in full, by resizing the app window manually (for really long names this can take a while).
> 

Seems like an enhancement rather than a bug fix.

> ### 7. Update schedules ordering when day passed
> We have this feature where the product would sort and separate schedules added by the user into two categories:
> 
> * Upcoming schedules (including ones that occur on current date)
> * Past schedules (those that occured before the current date)
> 
> Currently when the day has passed (date changes to the next day’s date), using of any of the commands does not update the schedules order (move schedules that have occured on that given date to past schedules). The only way to force this update is to make an edit to a schedule which will update the filtered list of schedules and hence causing a UI update.
> 
> We have modified all schedule commands to always sort the list when executed.

OK, if the current UI is showing incorrect data (e.g., past items being shown as upcoming)

> ### 8. Malformed json causing app to crash
> It was stated in the FAQ of feature freeze that the app should support manual edits to the json file. We have updated the product to meet that level of support.
> 
> However we did not include the section on support for manual edits to the json file like AB3 did.
 
Check tP constraints to see if support for editing the file is required. If required, it should be mentioned in the UG.

> ### 9. Parsing an Index with a number that is too large returns wrong error message
> When parsing a command that uses an index as a parameter, if the index provided is too large (e.g. 99999999999), the parser fails to parse it as an integer and treats it as an invalid parameter and returns an `Invalid command format` error instead of `Invalid index`.
> 
> Are we allowed to modify this behaviour to return the correct message by checking if the input is made entirely of numbers before trying to parse as an integer?

You can mention the upper limit of the index in the UG. That way, exceeding that will become an invalid format, which means the error message can stay the same.

**Comment by mfjkri** [comment]
Thank you for the clarifications!!

I have a follow question regarding:

> Only if multiple m/ causes the application to misbehave (i.e., crash, give incorrect results, or hinder normal usage). If the application gives the same (or similar) behavior with multiple m/ as it would with a single m/, the behavior is not incorrect (just more forgiving).

Can I check what is considered as incorrect results?

The mark command was intended to only accept 1 prefix like the name prefix `n/` in AB3.
However its current behaviour is such that a series of `m/0 m/0 m/1` would only use the last provided prefix `m/1`, discarding the previous ones.

Is this considered an incorrect result?

**Comment by nknguyenhc** [comment]
Hi prof, our team face a similar issue with number 9, but our case is slightly more complex as we use the same index parsing logic in two cases:

1. For parsing preamble. If the index is small and invalid, the error message is `invalid person index`. If the index is large, the error message is `invalid command index`. This might not be considered a bug as the error message may not give incorrect information.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/87511888/87ea80ff-a865-435f-9aa8-26dddc2d937a)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/87511888/7bdc1442-bb66-492e-9f4b-6610dbbd8a5d)

2. For parsing index of the item. If the index is small and invalid, the error message is `invalid index`. If the index is large, the error message is `index is not a non-zero unsigned integer`. This can be considered a bug because the large integer is still a non-zero unsigned integer.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/87511888/6a1fcf91-ef89-4aa5-9992-d354a6b3949b)

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/87511888/266b100e-691e-46f1-ae73-0d19d9d2c8d0)

We realised that while trying to fix the second case, the code changes will also be fixing the first case. May we ask if we are allowed to fix the parsing logic to handle large integers in this case?

**Comment by damithc** [comment]
> The mark command was intended to only accept 1 prefix like the name prefix `n/` in AB3. However its current behaviour is such that a series of `m/0 m/0 m/1` would only use the last provided prefix `m/1`, discarding the previous ones.
> 
> Is this considered an incorrect result?


Not necessarily. Just mention this behavior in the UG.
Interesting fact: Accepting multiple parameters was a 'feature' in earlier versions of AB3, with the rationale that it allows a user to quickly override an incorrect value of a parameter because for a fast typist it is faster to type the parameter again with the correct value rather than navigate back to the previous location to correct the incorrect value.

**Comment by damithc** [comment]
> 1. For parsing preamble. If the index is small and invalid, the error message is `invalid person index`. If the index is large, the error message is `invalid command index`. This might not be considered a bug as the error message may not give incorrect information.

@nknguyenhc 

Perhaps this can be remedied by updating the UG to mention the range of numbers accepted as an index?


> 2\. For parsing index of the item. If the index is small and invalid, the error message is `invalid index`. If the index is large, the error message is `index is not a non-zero unsigned integer`. This can be considered a bug because the large integer is still a non-zero unsigned integer.

Yes,  this is incorrect and can be fixed.

**Comment by damithc** [comment]
> We realised that while trying to fix the second case, the code changes will also be fixing the first case. May we ask if we are allowed to fix the parsing logic to handle large integers in this case?

@nknguyenhc Yes, that is fine (because the 2nd case is allowed to be fixed).

**Comment by nknguyenhc** [comment]
Alright, thanks prof!

**Comment by mfjkri** [comment]
> > The mark command was intended to only accept 1 prefix like the name prefix `n/` in AB3. However its current behaviour is such that a series of `m/0 m/0 m/1` would only use the last provided prefix `m/1`, discarding the previous ones.
> > Is this considered an incorrect result?
> 
> Not necessarily. Just mention this behavior in the UG. Interesting fact: Accepting multiple parameters was a 'feature' in earlier versions of AB3, with the rationale that it allows a user to quickly override an incorrect value of a parameter because for a fast typist it is faster to type the parameter again with the correct value rather than navigate back to the previous location to correct the incorrect value.

Okay I see!

Does that mean if we take, accepting only the last prefix to be the correct behaviour then `theme` using only the first keyword is taken to be an incorrect behaviour?

**Comment by damithc** [comment]
> Does that mean if we take, accepting only the last prefix to be the correct behaviour then `theme` using only the first keyword is taken to be an incorrect behaviour?

@nknguyenhc It is not incorrect to use the first one occurrence. Some choices may be better than others, but moving from the current not-incorrect choice to a one you think is better is an enhancement, not a bug fix.
