### ISSUE TITLE
Questioning if fixing the index displayed violates v1.4 constraint

### ISSUE THREAD

**Issue by Clin-lyx** [nus-cs2103-AY2324S1/forum#408]
Hi! An issue received in the PE-Dry run, suggests the Patient Card displayed has a wrong index. 
In the issue's example, after entering command view 3, in the PATIENT BEING VIEWED section,  the index in the left top corner should be 3 instead of 1.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/110957868/72dc9c3f-db41-42e3-8f08-91b9aa8cfea1)

Now the patient index is displayed correctly, but I am not sure if this violates v1.4 constraints.
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/110957868/8e7307f4-c2e7-4bc5-a87b-7d7ee12b621f)

**Comment by damithc** [comment]
@Clin-lyx hmm... this one is a bit tricky. What happens if you pin this patient. Does the index in right column become 3 as well?

**Comment by Clin-lyx** [comment]
The index will be 2
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/110957868/2ba6b1e1-41cd-4798-b520-d8c119d2abd8)

**Comment by damithc** [comment]
@Clin-lyx So, it seems the lists in the UI are just 1-indexed list, and the same item can appear in the multiple lists with different index numbers, based on the position of the item in that list. So, the original behavior of showing 1 is not strictly incorrect.

Besides, if you run `view 3`  (and show it as index 3 in the view panel) followed by `delete 2` (which will change the index of Charlotte to 2 in the middle list), the index of this item will not match across lists anyway. Perhaps the best is to not show a number at all in the 'view' panel (as it contains only one item) but that would be an enhancement rather than a bug fix.

**Comment by Clin-lyx** [comment]
Sorry just to make sure. So should I just revert the changes (letting the index in the Patient Being Viewed section be 1 for all patients after the view command) or can I keep the corrected index and add more detail in UG?

**Comment by damithc** [comment]
> Sorry just to make sure. So should I just revert the changes (letting the index in the Patient Being Viewed section be 1 for all patients after the view command) or can I keep the corrected index and add more detail in UG?

@Clin-lyx should revert to the original behavior.

**Comment by Clin-lyx** [comment]
Thanks! I will close this issue.
