### ISSUE TITLE
Clarification for whether the following changes violate feature freeze

### ISSUE THREAD

**Issue by teozern1** [nus-cs2103-AY2324S1/forum#413]
1. Users are allowed to add assignments with titles which show up in a panel on the UI. Assignment titles have no current restrictions but when the title is too long it is truncated to fit in the UI. If I add a restriction does it violate the feature freeze? 
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/75937968/29c52768-a8a5-457e-8b32-c4b79cf7b424)
Above shows the UI after using the command `addAssignment assngn/` with a very long parameter (stretches out of the command box)

2. Using search command to search by string originally only found the exact string but was changed so that any substring works. The UG wording as of v1.3 was unclear which was intended.
3. Originally search command allowed for multiple names, but was changed to 1 name. Though it was not explicitly stated in v1.3 that you could search for multiple names, searching for multiple names always returned no users anyway.
4. Our app allows the user to create tutorials representing NUS tutorials. We found a bug that users can put an empty string as tutorial name. This was not previously put in the UG. Can we fix this?
5. Our app had some renmants of AddressBook that do not affect the functions of the product. This includes "AddressBook" being put into the logs and as the product name at the top of JavaFX. Can we fix this?
6.  To add a module we use the `addModule` command which checks for a module name length of more than 5 characters (length not specified in the 1.3 UG). It is fine to add a restriction such that the length is more than 5 but less than 8 characters?
7. Previously UG states that alphanumeric characters are all accepted for the name of the module but the actual command does not accept lowercase letters. Is it fine to fix it to include lowercase letters?

**Comment by damithc** [comment]
@teozern1 

> * Users are allowed to add assignments with titles which show up in a panel on the UI. Assignment titles have no current restrictions but when the title is too long it is truncated to fit in the UI. If I add a restriction does it violate the feature freeze?
>   ![image](https://user-images.githubusercontent.com/75937968/282242030-29c52768-a8a5-457e-8b32-c4b79cf7b424.png)
>   Above shows the UI after using the command `addAssignment assngn/` with a very long parameter (stretches out of the command box)

The following applies:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/eed2226b-dd2d-447d-95da-06e1367b4243)


> * Using search command to search by string originally only found the exact string but was changed so that any substring works. The UG wording as of v1.3 was unclear which was intended.

As the original behavior was not incorrect, this change seems like an enhancement. The original behavior should be kept, and the UG should be updated to clarify the exact behavior. A more flexible search can be listed as a planned enhancement.

> * Originally search command allowed for multiple names, but was changed to 1 name. Though it was not explicitly stated in v1.3 that you could search for multiple names, searching for multiple names always returned no users anyway.

Can give an example? What happens if the user searches for `Alex Yeoh`? This person exists but there are two words being searched.

> * Our app allows the user to create tutorials representing NUS tutorials. We found a bug that users can put an empty string as tutorial name. This was not previously put in the UG. Can we fix this?

OK, but only if accepting an empty string causes the application be misbehave. See below:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/a84fee8b-c764-423d-ad5d-ef6c7819aba4)


> * Our app had some renmants of AddressBook that do not affect the functions of the product. This includes "AddressBook" being put into the logs and as the product name at the top of JavaFX. Can we fix this?

Yes.

> * To add a module we use the `addModule` command which checks for a module name length of more than 5 characters (length not specified in the 1.3 UG). It is fine to add a restriction such that the length is more than 5 but less than 8 characters?

Only if the current behavior causes the application to misbehave. Otherwise it is a nice-to-have enhancement which can be listed as a planned enhancement.

> * Previously UG states that alphanumeric characters are all accepted for the name of the module but the actual command does not accept lowercase letters. Is it fine to fix it to include lowercase letters?

Assuming the current behavior rejects legit names in way that hinders regular use, OK to fix.

**Comment by teozern1** [comment]
Thank you!
