### ISSUE TITLE
What should be inside the glossary for developer guide?

### ISSUE THREAD

**Issue by papataco14** [nus-cs2103-AY2324S1/forum#424]
Hi prof! I would like to clarify a few things about the glossary for the DG. 
1. Should it include or exclude the terms already defined in the glossary for the UserGuide? 
2. What are some examples of unnecessary terms? The textbook suggests that the glossary is to be used for all the stakeholders, so I'm not sure on what basis I should classify terms as unnecessary.

**Comment by damithc** [comment]
> 1. Should it include or exclude the terms already defined in the glossary for the UserGuide?

Can exclude them. For good measure, you can put a note in there to indicate which terms have been omitted because they are already defined in in the UG.


> 2\. What are some examples of unnecessary terms? The textbook suggests that the glossary is to be used for all the stakeholders, so I'm not sure on what basis I should classify terms as unnecessary.

DG is for developers. So, the glossary in there should be targeted for developers. The target audience is the basis for deciding if a term should or should not be included.

**Comment by papataco14** [comment]
Thank you for the clarification!
