### ISSUE TITLE
Software needed for PE

### ISSUE THREAD

**Issue by dhruvir29** [nus-cs2103-AY2324S1/forum#469]
May I check if we need to download Computer screen recorders like Panapto for the PE tomorrow?

**Comment by damithc** [comment]
@dhruvir29  No need. See below:

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/1673303/8a902f47-7ecb-4eb9-87c1-6a37c06fc804)

**Comment by dhruvir29** [comment]
Ok thanks. Also can I check if we are using a monitor, does our laptop need to be completely closed? Or would it be possible to only display on the monitor screen and not the laptop screen but use the keyboard and mouse of the laptop?

**Comment by damithc** [comment]
> Ok thanks. Also can I check if we are using a monitor, does our laptop need to be completely closed? Or would it be possible to only display on the monitor screen and not the laptop screen but use the keyboard and mouse of the laptop?

@dhruvir29 Yes, it needs to be closed or covered (e.g., drape a piece of paper over the screen so that you are not able to see it). Also, if you are using keyboard and the mouse of the laptop (while the screen is covered), it needs to be visible via the web cam. You are not allowed to use a keyboard or a mouse that we can't see through the Zoom feed.
