### ISSUE TITLE
Query about use cases in DG

### ISSUE THREAD

**Issue by flexibo** [nus-cs2103-AY2324S1/forum#501]
Is it a requirement to include a use case for every single command in the DG? 

(context: we missed out use case for one command, so not sure if we should accept the bug or put it under not in scope, since we also can't really find the requirements for use case)

**Comment by damithc** [comment]
@flexibo Use cases are used when the interaction between the user and the system is complicated enough to be documented. So, it is not a requirement to capture _every_ feature in the form of a use case.
However, if the DG seem to have use cases for less complicated interactions while not having use cases for more complicated interactions, that might be a mistake/oversight rather than a deliberate omission.

**Comment by flexibo** [comment]
is the `edit` command considered as complicated? not very sure what considers as complicated

**Comment by damithc** [comment]
@flexibo In this context, number of steps and number of extensions can be indicators of complexity.

**Comment by flexibo** [comment]
ah i see, ok thanks!
