### ISSUE TITLE
Question on validity of bugs

### ISSUE THREAD

**Issue by spatuly** [nus-cs2103-AY2324S1/forum#502]
In our DG, the target user profile was clearly documented as NUS TAs. However, in the UG, we only put "targeted towards TAs" in the introduction.

We understand that this is a valid documentation bug for the UG, and have accepted the bug reported. 

However, a tester seems to have misunderstood our target user profile, and reported several "feature flaw" bugs based on the "targeted towards TAs" in the UG, such as "this is too restrictive, other universities might have different ___". 

We were wondering if this is a valid bug report, since it was documented in the DG that our target user profile is NUS TAs, not TAs in general?

**Comment by damithc** [comment]
@spatuly If there is clear evidence that you meant to target the product for NUS TAs, you can evaluate bug reports based on that target user. If you wish, you can also say that expanding to a wider target user can be done in future versions, which opens the door for you to categorize those bugs as `NotInScope` rather than outright reject (in which case there's still no penalty for you but the tester will get some small amount of credit).
