### ISSUE TITLE
The functions of Ui and Parser classes

### ISSUE THREAD

**Issue by JasonRay168** [nus-cs2103-AY2324S1/forum#51]
Based on the project description, Ui "deals with interactions with the user", so is it safe to say that all System.out.println() lines are handled inside Ui? Or is this the job of the Parser instead?

**Comment by KamJiaYue** [comment]
It is safe to say that NOT ALL, BUT MOST of the System.out.println() should be handled in the UI, the parser is just for parsing user inputs, making sense of user inputs, handling user input errors etc.

**Comment by muhammadreyaaz** [comment]
There can be some strings returned by your own defined exceptions as well (so not all are handled by UI.) For example, if you handle your errors in the length of user input in Parser, a better way of abstraction would be to define your own exceptions and then return the String there, instead of system.out.println() in UI.

**Comment by JasonRay168** [comment]
Alright thanks very much!
