### ISSUE TITLE
Whether or not parsing of negative index and zero be considered a duplicate bug

### ISSUE THREAD

**Issue by yucongkoo** [nus-cs2103-AY2324S1/forum#512]
Hi, our team received multiple bug reports regarding the error message provided is less helpful when users inputed negative index/zero(e.g. `delete -1` would show a command format error rather than index out of bound error). This behaviour is expected as we specified that index should be in the range of `[1, 2147483647]`, which makes 0 and negative indices not a valid input to index, hence a command format error.

We are going to accept this bug as a NotInScope feature flaw, but we are not very sure whether or not both cases (i.e. 0 and negative indices) can be considered a duplicate or must he seperate bugs.

So the fix required is to modify the parse index method to not only accept unsigned positive integers, but also negative integers and zero, one could argue that these can be fixed separately (i.e. we can fix the parsing to accept zero but not negative and vice versa), but we think that since both zero and negative integers are within the same equivalence partition, it would also be valid to say both should be fixed together. That is, we think that they seem like one enhancement rather than two, as it wouldn't make sense to accept 0 which is already out of our current allowed indices range, but still reject negative indices.

However, we are not very sure can we merge these bugs as duplicate and is seeking advice here.

**Comment by damithc** [comment]
@yucongkoo it is best to go with the strict interpretation of the rule and treat them as separate bugs. If `NotInScope`, there is no penalty for you anyway. After all, the two cases may have been reported by two different testers.
For situations like grading rules in a large course like ours, it is better to go with the strict interpretation of the rule even when in a few cases it might give an unreasonable result. Reason: once we start allowing flexibility, every case will require a subjective decision, and no matter where we draw the line, there will always be cases very close to the line that wishes to be allowed.  To give an example from a different rule, we currently allow combining similar bug reports if there are at least 5 such bug reports. If we are not strict about this and allow a case of 4 very similar bugs to be combined (because it is close to 5), then someone will ask for 3 (because it is so close to 4), and then 2, and so on.

**Comment by yucongkoo** [comment]
@damithc Okay, totally understand, will be responding it as separate bugs. Thanks!
