### ISSUE TITLE
Feature Flaw Indirectly included in Planned Enhancement, but is still problematic

### ISSUE THREAD

**Issue by lihongguang00** [nus-cs2103-AY2324S1/forum#521]
Hi Prof,

[Bug Report Link](https://github.com/lihongguang00/pe/issues/8)

The bug report in question is a `feature flaw`. The current state of feature that I believe is flawed uses GUI buttons rather than keyboard (with no other alternative), which is makes it not keyboard friendly.  However, in one of the `Planned Enhancement`, they did mention adding CLI based commands that would indirectly address this feature flaw. However, my original argument was more of that the team has had their priorities wrong (since they could have spent the time implementing the GUI button into adding a `listener` to the GUI for keyboard support instead), and I was wondering if this would violate the module's PE guidelines if I were to reject their response (which they rejected the bug report), since it is technically addressed to some degree?

Thanks!

**Comment by damithc** [comment]
@lihongguang00 The _planned enhancement_ sections gives immunity even for cases that should be in scope of the current version (that's why that list is restricted in size). If a feature flaw is of lower priority, it doesn't need to be put it in the  _planned enhancement_ section because such feature flaws can be categorized as NotInScope, and escape the penalty that way.

**Comment by lihongguang00** [comment]
@damithc ah, I see, understood prof, thank you!
