### ISSUE TITLE
Addressing Functionality Bugs under Planned Enhancements

### ISSUE THREAD

**Issue by Tim-Siu** [nus-cs2103-AY2324S1/forum#524]
Hello!

I recently reviewed a team in PE and noticed some functionality bugs, specifically a non-responsive command when a parameter is missing. The team has listed this issue under planned enhancements. However, according to the textbook, planned enhancements are typically meant for addressing feature flaws, not for addressing functionality bugs. 

I'm a bit confused about whether covering a functionality bug under planned enhancements grants immunity from bug reports. With this understanding, I submitted a bug report, assuming that the planned enhancement does not exempt them from addressing the bug. However, the team marked my report as `NotInScope`. 

Could someone clarify if my bug report was appropriate in this context? And if so, was it correct for the team to classify it as `NotInScope`?

Thank you!

**Comment by damithc** [comment]
@Tim-Siu Sorry, I seem to have missed this earlier.

Planned enhancements were not meant to cover FunctionalityBugs, as such bugs were allowed to be fixed in v1.4

If the current behavior is reasonable, and seems to be a deliberate design decision (e.g., the UG explains the current behavior clearly or it is how normally such a feature behaves), then any further improvement corresponds to a FetureFlaw. Otherwise (ie., the problem seem to be caused by an oversight or incorrect logic), it is a FunctionalityBug.

**Comment by Tim-Siu** [comment]
> @Tim-Siu Sorry, I seem to have missed this earlier.
> 
> 
> 
> Planned enhancements were not meant to cover FunctionalityBugs, as such bugs were allowed to be fixed in v1.4
> 
> 
> 
> If the current behavior is reasonable, and seems to be a deliberate design decision (e.g., the UG explains the current behavior clearly or it is how normally such a feature behaves), then any further improvement corresponds to a FetureFlaw. Otherwise (ie., the problem seem to be caused by an oversight or incorrect logic), it is a FunctionalityBug. 
> 
> 
> 
> 

Thank you prof!!!
