### ISSUE TITLE
Committing code that has bugs/errors

### ISSUE THREAD

**Issue by Cikguseven** [nus-cs2103-AY2324S1/forum#54]
I would like to know if it's acceptable to commit code that might be buggy or have errors as it is still in progress. A scenario that usually occurs is development on different devices, where I have to commit the current code in order to continue on another device.

**Comment by damithc** [comment]
@Cikguseven Good question. From the iP requirements point of view, it is fine to do so. 
I'll let you guys discuss/share here your views/findings about this from a Git best practices point of view.

**Comment by HugeNoob** [comment]
In my opinion, there are two factors to consider:
1. How many people are working together on the repository?
2. Which branch are you pushing to?

For iP, since you're working alone on the project, it's probably quite reasonable to do so. If you don't like having buggy code in `master`, you could always branch out to resolve the code first, then merge back into `master` later on. If you really hate buggy commits in particular, you can do things like `git commit --amend` or `git rebase` to clear buggy commits after you fix them, but note that those will probably require a force push afterward.

For tP, you probably want to avoid pushing to branches that are shared with your group mates, in case they accidentally pull from them. I'm not sure what the tP structure is, but if it's done in forks, then it shouldn't be a big issue anyway.

**Comment by Cikguseven** [comment]
I think that's a reasonable approach. If the code is on an individual branch, then it seems acceptable to commit work in progress to it.
