### ISSUE TITLE
Issue with Scanners importing files

### ISSUE THREAD

**Issue by antonTan96** [nus-cs2103-AY2324S1/forum#55]
While working on Level-7, I encountered a strange issue:
```
File taskFile = new File(somePathToATxtFile);
            Scanner setup = new Scanner(taskFile);
           //some intermediate code 
            while(setup.hasNext()){
                //load task into the list
                //while loop does not loop
            }
```
In this piece of code, i try to initialize my list with tasks in the txt file, but the task is not loaded into the list.

```
File taskFile = new File(somePathToATxtFile);
            Scanner setup = new Scanner(taskFile);
           //some intermediate code 
           if(setup.hasNext()){
               System.out.println("hasNext"); //this piece of code runs!
           }
            while(setup.hasNext()){
                //load task into the list
                //while loop starts looping
            }
```
for some reason when I check if the setup scanner is empty or not, the tasks are now loaded into the list!

Can someone explain why checking if the scanner hasNext fixes this code?

**Comment by damithc** [comment]
@antonTan96 In your post above you have omitted some some that you think is not relevant to the problem. It is better to be sure. I suggest you put this code in a separate class and run it, to confirm you can reliably reproduce this problem without the code you have omitted in the post above. 

In other words, try to extract out a minimal but full version of the code that reproduces the problem reliably, and share that full code here so that both you and others are looking at the same code. You might even stumble on the answer while trying to extract out such a version of the code.

**Comment by antonTan96** [comment]
Apparently, I have found some crucial code that caused the while loop to terminate.
The problem is i tried to open a new FileWriter that passed in the same file in the Scanner.
Here is a code that demonstrates this: 
```
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;

public class ScannerTester {
    public static void main(String[] args){
        FileWriter writer = null;
        File taskFile = new File("./data/list.txt");
        Scanner setup = null ;

        try{
            setup = new Scanner(taskFile);
            writer = new FileWriter(taskFile);
        } catch (Exception e){
            System.out.println(e);
        }
        System.out.println(setup.hasNext());
        while(setup.hasNext()){
            System.out.println(setup.next());
        }
        

    }
} 
```
The output will be false.
Running setup.hasNext() before creating the FileWriter will fix the problem for some reason, and the while loop will start looping. This still confuses me.

**Comment by bobscodedump** [comment]
import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        File f = new File("./src/test.txt");
        try {
            Scanner s = new Scanner(f);
            while(s.hasNext()) {
                System.out.println("hi");
            }
        } catch (IOException e) {
            System.out.println(e);
        }
    }
}

tested your first code and it works, resulting in an infinite loop. maybe you could provide more details on what you included in your loop, or even your text file. next() and nextline() will progress the scanner, so maybe that's why your hasnext() is becoming false. hope this helps!

**Comment by StevenLiudw** [comment]
The issue arises because the FileWriter essentially truncates the file when it is opened for writing. This means that the contents of the file are erased, and the file becomes empty. As a result, when you subsequently call setup.hasNext() right after creating the FileWriter, it returns false because there are no more tokens to read – the file is empty.

**Comment by antonTan96** [comment]
Thanks for the answer! This certainly explains why I can't retrieve any more lines from the Scanner. However, this code below works for some reason.
```
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;

public class ScannerTester {
    public static void main(String[] args){
        FileWriter writer = null;
        File taskFile = new File("./data/list.txt");
        Scanner setup = null ;

        try{
            setup = new Scanner(taskFile);
            setup.hasNext(); //adding this line activates the loop
            writer = new FileWriter(taskFile);
        } catch (Exception e){
            System.out.println(e);
        }
        System.out.println(setup.hasNext());
        while(setup.hasNext()){
            System.out.println(setup.next());
        }
        

    }
} 
```
Here's how i understand this program:
After I input the file into the scanner, i check hasNext() and should return true (Have not opened filewriter yet)
Afterwards i open the fileWriter, flushing the entire file.
When check the condition of the while loop, it will fail and nothing will happen.

However, adding that one line before opening the fileWriter changes something and I'm not sure how.

**Comment by damithc** [comment]
Given below is what ChatGPT said when I asked why the code stops working when the `setup.hasNext();` is removed. What do you guys think about the ChatGPT's answer?

-----------

The reason the code stops working when you remove the `setup.hasNext();` statement inside the `try` block is due to how the `Scanner` class works in Java.

In Java, when you create a `Scanner` object to read from a file (or any input source), it initially points to the beginning of the input source. Calling `hasNext()` or `next()` on the `Scanner` advances its internal cursor to the next token in the input source. If you remove `setup.hasNext();` from the code, the `Scanner` object is not explicitly advanced to the next token, and as a result, the loop `while (setup.hasNext())` immediately checks the same token over and over again without advancing, causing an infinite loop.

Here's how the code works with and without the `setup.hasNext();` statement:

1. With `setup.hasNext();`:
   - The `Scanner` is created and initialized.
   - `setup.hasNext();` is called, which advances the cursor to the next token.
   - The `FileWriter` is created, which doesn't affect the `Scanner`.
   - The loop `while (setup.hasNext())` works correctly, reading and printing tokens until the end of the file.

2. Without `setup.hasNext();`:
   - The `Scanner` is created but not advanced to the next token.
   - The `FileWriter` is created, which doesn't affect the `Scanner`.
   - The loop `while (setup.hasNext())` starts, but since the cursor was not advanced, it immediately checks the same token repeatedly, resulting in an infinite loop.

If you want to remove the `setup.hasNext();` statement, you should ensure that the `Scanner` cursor is advanced in some way before entering the loop. You can do this by reading a token from the `Scanner` using `setup.next();` before the loop starts, like this:

```java
// Advance the cursor to the next token
if (setup.hasNext()) {
    setup.next();
}

// Now, the loop can work correctly
while (setup.hasNext()) {
    System.out.println(setup.next());
}
```

This way, you ensure that the `Scanner` cursor is properly positioned to read tokens within the loop.

**Comment by damithc** [comment]
@antonTan96 On a related note, perhaps keep reading and writing of files separate from each other. Currently, you use the same `File` object for both.
