### ISSUE TITLE
Practice Exam Part 3 [p.3.15] domain modelling: Why is class diagram the least useful for domain modelling?

### ISSUE THREAD

**Issue by garylow2001** [nus-cs2103-AY2324S1/forum#552]
This is the answer:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/97083001/5a4ce2d3-eb18-47eb-9f4a-f76668a6f499)

However, in the textbook, it mentions that class diagrams can be used to model the problem domain as well:
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/97083001/0abdb492-a45e-4813-9ea1-b7de11882fbc)

The way I interpreted it is since class diagrams can be OODMs, shouldn't it be useful for domain modelling? 
This makes the other options less useful for domain modelling.

**Comment by damithc** [comment]
@garylow2001 I agree that this question is a bit confusing. Would have been clearer is `OODM` was one of the options. The way the textbook is worded also adds to the confusion. I've made a note to reword it in the next version. 

This question tests two learning points:
1. Any model (not just UML models) can be used for domain modelling
2. Class diagrams are not used for domain modelling because there is a more optimized model we can use for the same purpose i.e., OODM

**Comment by garylow2001** [comment]
> @garylow2001 I agree that this question is a bit confusing. Would have been clearer is `OODM` was one of the options. The way the textbook is worded also adds to the confusion. I've made a note to reword it in the next version.
> 
> This question tests two learning points:
> 
> 1. Any model (not just UML models) can be used for domain modelling
> 2. Class diagrams are not used for domain modelling because there is a more optimized model we can use for the same purpose i.e., OODM

I understand, thank you!
