### ISSUE TITLE
JUnit Testing stops working after further increments

### ISSUE THREAD

**Issue by brendanneojw** [nus-cs2103-AY2324S1/forum#56]
Just wondering if anyone experienced this? My JUnit testing was working fine until when I implemented JavaDocs. When I start to try and run the test again, it shows "Test events were not received".
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/29995121/23071b6c-38b3-4453-9535-603c16abcc03)

**Comment by damithc** [comment]
> My JUnit testing was working fine until when I implemented JavaDocs.

@brendanneojw to confirm this hypothesis, you can checkout the commit just before you added JavaDocs, and try to run tests from there. If that works, the problem was indeed introduced by the JavaDoc commit (which means you can examine that doc to see if you can spot the change that potentially caused the test behavior to change).

Also, push the current code to a branch and share the link here so that someone else can try to reproduce the error on their end.

**Comment by brendanneojw** [comment]
Hi prof, i did the checkout at each branch before my final implementation at Level 9 and realised that JUnit testing does work already. I'm quite confused though because at certain branches it doesn't work but as some it does. However it seems like there may be file changes that could cause it and my master branch is able to perform the JUnit testing already. Thank you!
