### ISSUE TITLE
urgent issue when trying to push a commit

### ISSUE THREAD

**Issue by btaanish** [nus-cs2103-AY2324S1/forum#73]
I have been trying to push my recent merge commit but kee facing the following error:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Could somebody kindly advise on how to correct this issue. 

TIA!

**Comment by damithc** [comment]
@D-Limiter While waiting for inputs from others, perhaps specify what Git Client you are using to perform this action? If it was a CLI, which command did you use.

If using Sourcetree, you can refer to [this se-edu guide](https://se-education.org/guides/tutorials/sourcetree.html#connecting-sourcetree-to-your-github-account:~:text=Connecting%20Sourcetree%20to%20Your%20GitHub%20Account)

**Comment by btaanish** [comment]
Hi Prof, I used the commands git push origin master

**Comment by damithc** [comment]
@D-Limiter Which OS? Are you using any Git client? Were you able to push code before or is this the first time you are trying to push? 
Try to provide as much contextual information as possible so that others can zero in on the problem more easily.

**Comment by btaanish** [comment]
Thanks for the advise Prof.

For reference, I am using a macOS and this is the second time that I have tried pushing changes to my gitHub fork. It worked well for the purpose of week 2's ip but am unable to push any of the commits for week 3's iP tasks due to this authentication error. really unsure on how to proceed and submit my work for week 3's tasks. 

Any advise would be greatly appreciated!

Thanks

**Comment by damithc** [comment]
@D-Limiter Using Sourcetree, or some other Git client, or just plain Git only?

**Comment by btaanish** [comment]
> 

Just using plain git in this situation

**Comment by lipwei1808** [comment]
Did you register your SSH keys for your github account on your machine - is this the same machine you used to push for your week 2 ip?

**Comment by aliciamichellew** [comment]
Last time when I encounter this issue, I setup my SSH keys again. Not sure why it was missing, but doing it again solves the issue.

**Comment by raynertjx** [comment]
I think it has something to do with your SSH key. Maybe you can follow the above suggestions and reconfigure your SSH key.

**Comment by ravern** [comment]
## Verify your SSH keys

Did you create an SSH keypair on your system? If you didn't, perhaps in week 2 you used the HTTPS URL i.e. https://... instead of the SSH URL to fetch from GitHub, and perhaps you might want to revert to that i.e. `git remote set-url origin <http url>`.

Otherwise, can you check that your SSH keys exist and haven't changed. If you aren't sure where it is and didn't do any special configuration other than googling "how to create SSH key", you can usually find your key-pair at `~/.ssh`.

Run `cat ~/.ssh/id_rsa.pub` and check that there's some output that starts with `ssh-rsa`. **Do not `cat ~/.ssh/id_rsa` (notice there's no .pub file extension here) and never send the output from that anywhere.**

## Check your SSH keys on GitHub

Go to the SSH keys configuration page at https://github.com/settings/keys and check that there's at least one SSH key listed there. Ensure that your SSH key output from before (the `id_rsa.pub` file) matches the SSH key listed there. If it doesn't, create a new entry and add the output from before there.

**Again, do not do not do not copy and paste the output from `id_rsa`, copy the output from `id_rsa.pub`.**

**Comment by btaanish** [comment]
Thanks a lot, verifying and setting up the SSH keys worked!
