### ISSUE TITLE
Forgot to push one commit

### ISSUE THREAD

**Issue by ItsTYtan** [nus-cs2103-AY2324S1/forum#74]
I forgot to push one commit into Github. The code, however, does contain the features that the commit is supposed to have, it is just in another commit. (i.e. one commit has two of the increments for the week A-packages and Gradle). Should I push with the tags but on the A gradle commit, or is any action necessary as the code does have all the features for the IP project?

**Comment by rngzhi** [comment]
In week 2, it is specified on the website, "From this point onward, commit code at important points. Minimally, commit after completing each increment". Not sure if this will affect grades. Actually, I think we are supposed to separate each increment into different branches. According to your description, it seems like you are implementing it on the master branch only.

**Comment by damithc** [comment]
@ItsTYtan It is ideal if you commit at least after each increment. But it is not a big issue if you forgot to do so earlier. Remember to do so in future. The purpose of the iP is to help you learn the basics. Making mistakes, getting stuck, overshooting deadlines are a part of the learning process. There is no penalty as long as you learn from mistakes and recover/catch-up within a few days.


In this case, also push the corresponding tags so that the dashboard can detect that you have completed the increment. For the purpose of dashboard updates, it doesn't matter which commit the tag is on; as long as the tag is present in the fork (and reachable from the master branch), the item will turn green in the dashboard.

**Comment by eyelessrhyme7** [comment]
I think for this situation, just add a comment near the change or add documentation near the change, like for gradle, add a comment in the gradle file or even in the Duke file, just signalling that its a dummy commit and you've carried out the increment in a previous commit so you have some proof when it comes to grading. Shouldn't be an issue as pointed out by prof above but if you're apprehensive haha. And add a tag to the dummy commit, so the code gets recorded.

**Comment by lhy-hoyin** [comment]
Hello @ItsTYtan 
It looks like your issue has been resolved. If that is the case, perhaps you can close this issue. Otherwise, perhaps you can elaborate on what you still wish to clarify.

**Comment by ItsTYtan** [comment]
Thanks for all the help, Ill close the issue.
