### ISSUE TITLE
Warning on Loading JavaFX

### ISSUE THREAD

**Issue by inezkok** [nus-cs2103-AY2324S1/forum#86]
Hi I'm currently trying to implement GUI using FXML and the GUI works fine. However, when running the Launcher, I get the warning below.

![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/4095b448-1d82-4bdd-8ecd-a4f3e22c6ced)

I suspect that it is something related the version of my JavaFX and SceneBuilder so here is the details of my JavaFX:

-  I used the Gradle method to set up my JavaFX
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/04f694e4-ce17-4584-975d-97b56ffd3d1e)

- I downloaded the latest version SceneBuilder for my Mac
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/2e1566ed-d711-4e4d-9e2b-78a2cbf36487)
![image](https://github.com/nus-cs2103-AY2324S1/forum/assets/117144224/1b445fc8-9248-4e15-85e0-d93aed06d360)

I was wondering if there is any way to solve this warning?

**Comment by joel-foo** [comment]
Yes, because the Scene builder is v20, once you update the FXML file using Scene builder, the FXML will use the javafx v20. 

I think there are two ways to solve this
- Use scene builder v17

- In you fxml files, change the value of the xmlns attribute.

For example, change

`<fx:root alignment="TOP_RIGHT" maxHeight="1.7976931348623157E308" prefWidth="400.0" type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/20" xmlns:fx="http://javafx.com/fxml/1">`

to 

`<fx:root alignment="TOP_RIGHT" maxHeight="1.7976931348623157E308" prefWidth="400.0" type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1">`

will make the warning go away.

**Comment by joel-foo** [comment]
Yes, because the Scene builder is v20, once you update the FXML file using Scene builder, the FXML file will use javafx v20. 

I think there are two ways to solve this
1. Use scene builder v17 instead

or

2.  In you fxml files, after you are done with editing using scene builder, manually update the value of the `xmlns` attribute of the 1st XML opening tag.

For example, changing

`<fx:root alignment="TOP_RIGHT" maxHeight="1.7976931348623157E308" prefWidth="400.0" type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/20" xmlns:fx="http://javafx.com/fxml/1">`

to 

`<fx:root alignment="TOP_RIGHT" maxHeight="1.7976931348623157E308" prefWidth="400.0" type="javafx.scene.layout.HBox" xmlns="http://javafx.com/javafx/17" xmlns:fx="http://javafx.com/fxml/1">`

in the relevant xml files will make the warning go away. 

Note that if use method 2, you will have to update that everytime you change any files using Scene builder.

**Comment by inezkok** [comment]
Hi @joel-foo I used method 2 and it works! Thank you :)
